-- if true then return {} end -- WARN: REMOVE THIS LINE TO ACTIVATE THIS FILE

-- Customize Treesitter

---@type LazySpec
return {
  "nvim-treesitter/nvim-treesitter",
  opts = {
    ensure_installed = {
      "awk",
      "bash",
      "c",
      "css",
      "csv",
      "diff",
      "git_config",
      "git_rebase",
      "gitattributes",
      "gitcommit",
      "gitignore",
      "go",
      "gomod",
      "gosum",
      "gotmpl",
      "groovy",
      "html",
      "http",
      "java",
      "javascript",
      "jq",
      "json",
      "json5",
      "jsonc",
      "kotlin",
      "lua",
      "make",
      "markdown_inline",
      "markdown",
      "perl",
      "python",
      "ruby",
      "rust",
      "sql",
      "ssh_config",
      "swift",
      "toml",
      "tsv",
      "typescript",
      "vim",
      "vimdoc",
      "xml",
      "yaml",
    },
  },
}
