@startuml homebrew
skinparam usecase {
    BorderColor DarkSlateGray
    BackgroundColor DarkSeaGreen
    BackgroundColor<< req >> ForestGreen
    BackgroundColor<< dep >> DarkGoldenRod
}
(abseil) << dep >>
(ant)
(ant)-->(openjdk)
(aom) << dep >>
(aom)-->(jpeg-xl)
(aom)-->(libvmaf)
(apr) << dep >>
(apr-util) << dep >>
(apr-util)-->(apr)
(apr-util)-->(openssl@3)
(aria2)
(aria2)-->(gettext)
(aria2)-->(libssh2)
(aria2)-->(openssl@3)
(aria2)-->(sqlite)
(autojump)
(autojump)-->(python@3.13)
(azhuchkov/tools/tunblkctl)
(bash)
(bash-completion@2)
(bash-completion@2)-->(bash)
(bash-language-server)
(bash-language-server)-->(node)
(bat)
(bat)-->(libgit2)
(bat)-->(oniguruma)
(bfg)
(bfg)-->(openjdk)
(biome)
(black)
(black)-->(python@3.13)
(bpytop)
(bpytop)-->(osx-cpu-temp)
(bpytop)-->(python@3.13)
(brotli) << dep >>
(c-ares) << dep >>
(ca-certificates) << dep >>
(caddy)
(cairo) << dep >>
(cairo)-->(fontconfig)
(cairo)-->(freetype)
(cairo)-->(gettext)
(cairo)-->(glib)
(cairo)-->(libpng)
(cairo)-->(libx11)
(cairo)-->(libxcb)
(cairo)-->(libxext)
(cairo)-->(libxrender)
(cairo)-->(lzo)
(cairo)-->(pixman)
(capstone) << dep >>
(capstone)-->(gettext)
(certifi) << dep >>
(certifi)-->(ca-certificates)
(chafa)
(chafa)-->(cairo)
(chafa)-->(freetype)
(chafa)-->(gdk-pixbuf)
(chafa)-->(gettext)
(chafa)-->(glib)
(chafa)-->(jpeg-turbo)
(chafa)-->(jpeg-xl)
(chafa)-->(libavif)
(chafa)-->(librsvg)
(chafa)-->(libtiff)
(chafa)-->(webp)
(choose-rust)
(clang-format)
(cmake)
(cmake-language-server)
(cmake-language-server)-->(python@3.13)
(codespell)
(codespell)-->(python@3.13)
(colima)
(colima)-->(lima)
(cpanminus)
(croc)
(curl)
(curl)-->(brotli)
(curl)-->(libnghttp2)
(curl)-->(libssh2)
(curl)-->(openssl@3)
(curl)-->(rtmpdump)
(curl)-->(zstd)
(curlie)
(delve)
(deno)
(deno)-->(little-cms2)
(deno)-->(sqlite)
(di)
(direnv)
(direnv)-->(bash)
(dive)
(dmalloc)
(dockerfile-language-server)
(dockerfile-language-server)-->(node)
(dotnet@8) << dep >>
(dotnet@8)-->(icu4c@77)
(dotnet@8)-->(openssl@3)
(dtc) << dep >>
(dufs)
(dust)
(eza)
(eza)-->(libgit2)
(fd)
(fdupes)
(fdupes)-->(pcre2)
(figlet)
(file-formula)
(file-formula)-->(libmagic)
(flake8)
(flake8)-->(python@3.13)
(fontconfig) << dep >>
(fontconfig)-->(freetype)
(fossil)
(fossil)-->(openssl@3)
(freetype) << dep >>
(freetype)-->(libpng)
(fribidi) << dep >>
(fzf)
(gawk)
(gawk)-->(gettext)
(gawk)-->(gmp)
(gawk)-->(mpfr)
(gawk)-->(readline)
(gd) << dep >>
(gd)-->(fontconfig)
(gd)-->(freetype)
(gd)-->(jpeg-turbo)
(gd)-->(libavif)
(gd)-->(libpng)
(gd)-->(libtiff)
(gd)-->(webp)
(gdk-pixbuf) << dep >>
(gdk-pixbuf)-->(gettext)
(gdk-pixbuf)-->(glib)
(gdk-pixbuf)-->(jpeg-turbo)
(gdk-pixbuf)-->(libpng)
(gdk-pixbuf)-->(libtiff)
(gettext) << dep >>
(gettext)-->(libunistring)
(gh)
(giflib) << dep >>
(git)
(git)-->(gettext)
(git)-->(pcre2)
(git-delta)
(git-delta)-->(libgit2)
(git-delta)-->(oniguruma)
(git-lfs)
(git-secret)
(git-secret)-->(gawk)
(git-secret)-->(gnupg)
(git-svn)
(git-svn)-->(git)
(git-svn)-->(subversion)
(glab)
(glib) << dep >>
(glib)-->(gettext)
(glib)-->(pcre2)
(gmp) << dep >>
(gmssl)
(gnu-getopt)
(gnu-sed)
(gnu-tar)
(gnupg)
(gnupg)-->(gettext)
(gnupg)-->(gnutls)
(gnupg)-->(libassuan)
(gnupg)-->(libgcrypt)
(gnupg)-->(libgpg-error)
(gnupg)-->(libksba)
(gnupg)-->(libusb)
(gnupg)-->(npth)
(gnupg)-->(pinentry)
(gnupg)-->(readline)
(gnutls) << dep >>
(gnutls)-->(ca-certificates)
(gnutls)-->(gettext)
(gnutls)-->(gmp)
(gnutls)-->(libidn2)
(gnutls)-->(libtasn1)
(gnutls)-->(libunistring)
(gnutls)-->(nettle)
(gnutls)-->(p11-kit)
(gnutls)-->(unbound)
(go)
(gofumpt)
(gofumpt)-->(go)
(goimports)
(goimports)-->(go)
(gomodifytags)
(gopls)
(gost)
(gotags)
(gotests)
(gpgme) << dep >>
(gpgme)-->(gnupg)
(gpgme)-->(libassuan)
(gpgme)-->(libgpg-error)
(gradle)
(gradle)-->(openjdk)
(graphite2) << dep >>
(graphviz) << dep >>
(graphviz)-->(cairo)
(graphviz)-->(fontconfig)
(graphviz)-->(freetype)
(graphviz)-->(gd)
(graphviz)-->(gdk-pixbuf)
(graphviz)-->(gettext)
(graphviz)-->(glib)
(graphviz)-->(gts)
(graphviz)-->(harfbuzz)
(graphviz)-->(libpng)
(graphviz)-->(librsvg)
(graphviz)-->(libtool)
(graphviz)-->(pango)
(graphviz)-->(webp)
(grpcurl)
(gts) << dep >>
(gts)-->(gettext)
(gts)-->(glib)
(gts)-->(netpbm)
(gwt)
(gwt)-->(openjdk)
(hadolint)
(harelba/q/q)
(harfbuzz) << dep >>
(harfbuzz)-->(cairo)
(harfbuzz)-->(freetype)
(harfbuzz)-->(glib)
(harfbuzz)-->(graphite2)
(harfbuzz)-->(icu4c@77)
(hazelcast/hz/hazelcast)
(hazelcast/hz/hazelcast)-->(openjdk@21)
(hazelcast/hz/hazelcast-management-center)
(hazelcast/hz/hazelcast-management-center)-->(openjdk@21)
(hexyl)
(hgrep)
(highway) << dep >>
(htop)
(htop)-->(ncurses)
(httpie)
(httpie)-->(certifi)
(httpie)-->(python@3.13)
(hyperfine)
(icu4c@77) << dep >>
(imath) << dep >>
(iperf3)
(iperf3)-->(openssl@3)
(ipython)
(ipython)-->(python@3.13)
(jasper) << dep >>
(jasper)-->(jpeg-turbo)
(jpeg-turbo) << dep >>
(jpeg-xl) << dep >>
(jpeg-xl)-->(brotli)
(jpeg-xl)-->(giflib)
(jpeg-xl)-->(highway)
(jpeg-xl)-->(imath)
(jpeg-xl)-->(jpeg-turbo)
(jpeg-xl)-->(libpng)
(jpeg-xl)-->(little-cms2)
(jpeg-xl)-->(openexr)
(jpeg-xl)-->(webp)
(jq)
(jq)-->(oniguruma)
(kotlin-language-server)
(kotlin-language-server)-->(openjdk@21)
(krb5) << dep >>
(krb5)-->(openssl@3)
(ktlint)
(ktlint)-->(openjdk)
(lazygit)
(libassuan) << dep >>
(libassuan)-->(libgpg-error)
(libavif) << dep >>
(libavif)-->(aom)
(libavif)-->(jpeg-turbo)
(libavif)-->(libpng)
(libcbor) << dep >>
(libdeflate) << dep >>
(libevent) << dep >>
(libevent)-->(openssl@3)
(libfido2) << dep >>
(libfido2)-->(libcbor)
(libfido2)-->(openssl@3)
(libgcrypt) << dep >>
(libgcrypt)-->(libgpg-error)
(libgit2) << dep >>
(libgit2)-->(libssh2)
(libgpg-error) << dep >>
(libgpg-error)-->(gettext)
(libidn2) << dep >>
(libidn2)-->(gettext)
(libidn2)-->(libunistring)
(libksba) << dep >>
(libksba)-->(libgpg-error)
(liblinear) << dep >>
(libmagic) << dep >>
(libnghttp2) << dep >>
(libpng) << dep >>
(librsvg) << dep >>
(librsvg)-->(cairo)
(librsvg)-->(fontconfig)
(librsvg)-->(freetype)
(librsvg)-->(gdk-pixbuf)
(librsvg)-->(gettext)
(librsvg)-->(glib)
(librsvg)-->(harfbuzz)
(librsvg)-->(libpng)
(librsvg)-->(pango)
(libslirp) << dep >>
(libslirp)-->(glib)
(libssh) << dep >>
(libssh)-->(openssl@3)
(libssh2) << dep >>
(libssh2)-->(openssl@3)
(libtasn1) << dep >>
(libtiff) << dep >>
(libtiff)-->(jpeg-turbo)
(libtiff)-->(xz)
(libtiff)-->(zstd)
(libtool) << dep >>
(libtool)-->(m4)
(libunistring) << dep >>
(libusb) << dep >>
(libuv) << dep >>
(libvmaf) << dep >>
(libx11) << dep >>
(libx11)-->(libxcb)
(libx11)-->(xorgproto)
(libxau) << dep >>
(libxau)-->(xorgproto)
(libxcb) << dep >>
(libxcb)-->(libxau)
(libxcb)-->(libxdmcp)
(libxdmcp) << dep >>
(libxdmcp)-->(xorgproto)
(libxext) << dep >>
(libxext)-->(libx11)
(libxext)-->(xorgproto)
(libxrender) << dep >>
(libxrender)-->(libx11)
(libxrender)-->(xorgproto)
(libyaml) << dep >>
(lima) << dep >>
(liquibase)
(liquibase)-->(openjdk)
(little-cms2) << dep >>
(little-cms2)-->(jpeg-turbo)
(little-cms2)-->(libtiff)
(llvm@19) << dep >>
(llvm@19)-->(xz)
(llvm@19)-->(zstd)
(lpeg) << dep >>
(lrzsz)
(lua)
(lua-language-server)
(luacheck)
(luacheck)-->(lua)
(luajit) << dep >>
(luv) << dep >>
(luv)-->(libuv)
(lz4) << dep >>
(lzo) << dep >>
(m4) << dep >>
(macmon)
(make)
(markdown-toc)
(markdown-toc)-->(node)
(markdownlint-cli2)
(markdownlint-cli2)-->(node)
(marksman)
(marksman)-->(dotnet@8)
(mas)
(maven)
(maven)-->(openjdk)
(miniserve)
(miniupnpc)
(mkcert)
(mongodb/brew/mongodb-community)
(moonfruit/tap/doge)
(moonfruit/tap/geo)
(moonfruit/tap/gost@3)
(moonfruit/tap/impl)
(moonfruit/tap/impl)-->(go)
(moonfruit/tap/lzc-cli)
(moonfruit/tap/lzc-cli)-->(node)
(moonfruit/tap/openssl@1.0)
(moonfruit/tap/openssl@1.0)-->(ca-certificates)
(moonfruit/tap/oracle-instantclient)
(moonfruit/tap/p7zip-all)
(moonfruit/tap/tongsuo) << dep >>
(moonfruit/tap/tongsuo)-->(ca-certificates)
(moonfruit/tap/tscurl)
(moonfruit/tap/tscurl)-->(brotli)
(moonfruit/tap/tscurl)-->(libnghttp2)
(moonfruit/tap/tscurl)-->(moonfruit/tap/tongsuo)
(moonfruit/tap/tscurl)-->(zstd)
(moonfruit/tap/uutils-selected)
(moonfruit/tap/wlp-webprofile8)
(moonfruit/tap/wlp-webprofile8)-->(openjdk)
(mosh)
(mosh)-->(protobuf)
(mpdecimal) << dep >>
(mpfr) << dep >>
(mpfr)-->(gmp)
(mysql-client)
(mysql-client)-->(libfido2)
(mysql-client)-->(openssl@3)
(mysql-client)-->(zlib)
(mysql-client)-->(zstd)
(ncdu)
(ncdu)-->(ncurses)
(ncdu)-->(zstd)
(ncruces/tap/zenity)
(ncurses) << dep >>
(neovim)
(neovim)-->(gettext)
(neovim)-->(libuv)
(neovim)-->(lpeg)
(neovim)-->(luajit)
(neovim)-->(luv)
(neovim)-->(tree-sitter)
(neovim)-->(unibilium)
(neovim)-->(utf8proc)
(netpbm) << dep >>
(netpbm)-->(jasper)
(netpbm)-->(jpeg-turbo)
(netpbm)-->(libpng)
(netpbm)-->(libtiff)
(nettle) << dep >>
(nettle)-->(gmp)
(nmap)
(nmap)-->(liblinear)
(nmap)-->(libssh2)
(nmap)-->(lua)
(nmap)-->(openssl@3)
(nmap)-->(pcre2)
(node)
(node)-->(brotli)
(node)-->(c-ares)
(node)-->(icu4c@77)
(node)-->(libnghttp2)
(node)-->(libuv)
(node)-->(openssl@3)
(npth) << dep >>
(nspr) << dep >>
(nss) << dep >>
(nss)-->(nspr)
(nushell)
(nushell)-->(openssl@3)
(ollama)
(oniguruma) << dep >>
(opencc)
(openexr) << dep >>
(openexr)-->(imath)
(openexr)-->(libdeflate)
(openjdk)
(openjdk)-->(freetype)
(openjdk)-->(giflib)
(openjdk)-->(harfbuzz)
(openjdk)-->(jpeg-turbo)
(openjdk)-->(libpng)
(openjdk)-->(little-cms2)
(openjdk@11)
(openjdk@11)-->(freetype)
(openjdk@11)-->(giflib)
(openjdk@11)-->(harfbuzz)
(openjdk@11)-->(jpeg-turbo)
(openjdk@11)-->(libpng)
(openjdk@11)-->(little-cms2)
(openjdk@17)
(openjdk@17)-->(freetype)
(openjdk@17)-->(giflib)
(openjdk@17)-->(harfbuzz)
(openjdk@17)-->(jpeg-turbo)
(openjdk@17)-->(libpng)
(openjdk@17)-->(little-cms2)
(openjdk@21)
(openjdk@21)-->(freetype)
(openjdk@21)-->(giflib)
(openjdk@21)-->(harfbuzz)
(openjdk@21)-->(jpeg-turbo)
(openjdk@21)-->(libpng)
(openjdk@21)-->(little-cms2)
(openjpeg) << dep >>
(openjpeg)-->(libpng)
(openjpeg)-->(libtiff)
(openjpeg)-->(little-cms2)
(openssl@3) << dep >>
(openssl@3)-->(ca-certificates)
(osx-cpu-temp) << dep >>
(oven-sh/bun/bun)
(p11-kit) << dep >>
(p11-kit)-->(ca-certificates)
(p11-kit)-->(libtasn1)
(pandoc)
(pango) << dep >>
(pango)-->(cairo)
(pango)-->(fontconfig)
(pango)-->(freetype)
(pango)-->(fribidi)
(pango)-->(glib)
(pango)-->(harfbuzz)
(parallel)
(pcre) << dep >>
(pcre2) << dep >>
(pigz)
(pigz)-->(zopfli)
(pinentry) << dep >>
(pinentry)-->(libassuan)
(pinentry)-->(libgpg-error)
(pinentry-mac)
(pinentry-mac)-->(libassuan)
(pinentry-mac)-->(libgpg-error)
(pipgrip)
(pipgrip)-->(python@3.13)
(pixman) << dep >>
(pkgconf) << dep >>
(plantuml)
(plantuml)-->(graphviz)
(plantuml)-->(openjdk)
(poppler)
(poppler)-->(cairo)
(poppler)-->(fontconfig)
(poppler)-->(freetype)
(poppler)-->(gettext)
(poppler)-->(glib)
(poppler)-->(gpgme)
(poppler)-->(jpeg-turbo)
(poppler)-->(libassuan)
(poppler)-->(libpng)
(poppler)-->(libtiff)
(poppler)-->(little-cms2)
(poppler)-->(nspr)
(poppler)-->(nss)
(poppler)-->(openjpeg)
(popt) << dep >>
(postgresql@16)
(postgresql@16)-->(gettext)
(postgresql@16)-->(icu4c@77)
(postgresql@16)-->(krb5)
(postgresql@16)-->(lz4)
(postgresql@16)-->(openssl@3)
(postgresql@16)-->(readline)
(postgresql@16)-->(zstd)
(prettier)
(prettier)-->(node)
(protobuf) << dep >>
(protobuf)-->(abseil)
(proxychains-ng)
(pstree)
(pup)
(pv)
(pv)-->(gettext)
(pyright)
(pyright)-->(node)
(python@3.13) << dep >>
(python@3.13)-->(mpdecimal)
(python@3.13)-->(openssl@3)
(python@3.13)-->(sqlite)
(python@3.13)-->(xz)
(qemu)
(qemu)-->(capstone)
(qemu)-->(dtc)
(qemu)-->(glib)
(qemu)-->(gnutls)
(qemu)-->(jpeg-turbo)
(qemu)-->(libpng)
(qemu)-->(libslirp)
(qemu)-->(libssh)
(qemu)-->(libusb)
(qemu)-->(lzo)
(qemu)-->(ncurses)
(qemu)-->(nettle)
(qemu)-->(pixman)
(qemu)-->(snappy)
(qemu)-->(vde)
(qemu)-->(zstd)
(qsv)
(rcs)
(readline) << dep >>
(redis)
(redis)-->(openssl@3)
(ripgrep)
(ripgrep)-->(pcre2)
(rlwrap)
(rlwrap)-->(readline)
(rsync)
(rsync)-->(lz4)
(rsync)-->(openssl@3)
(rsync)-->(popt)
(rsync)-->(xxhash)
(rsync)-->(zstd)
(rtmpdump) << dep >>
(rtmpdump)-->(openssl@3)
(ruby)
(ruby)-->(libyaml)
(ruby)-->(openssl@3)
(ruff)
(rust)
(rust)-->(libgit2)
(rust)-->(libssh2)
(rust)-->(llvm@19)
(rust)-->(openssl@3)
(rust)-->(pkgconf)
(rust)-->(zstd)
(sd)
(shellcheck)
(shfmt)
(sing-box)
(sk)
(snappy) << dep >>
(sponge)
(sqlfluff)
(sqlfluff)-->(libyaml)
(sqlfluff)-->(python@3.13)
(sqlite) << dep >>
(sqlite)-->(readline)
(sshpass)
(staticcheck)
(staticcheck)-->(go)
(stylua)
(subversion)
(subversion)-->(apr)
(subversion)-->(apr-util)
(subversion)-->(gettext)
(subversion)-->(lz4)
(subversion)-->(openssl@3)
(subversion)-->(utf8proc)
(superfile)
(swift-format)
(taplo)
(tcping)
(teamookla/speedtest/speedtest)
(testssl)
(testssl)-->(openssl@3)
(tmux)
(tmux)-->(libevent)
(tmux)-->(ncurses)
(tmux)-->(utf8proc)
(tokei)
(tomcat)
(tomcat)-->(openjdk)
(tomcat-native)
(tomcat-native)-->(apr)
(tomcat-native)-->(openjdk)
(tomcat-native)-->(openssl@3)
(tomcat@10)
(tomcat@10)-->(openjdk)
(tomcat@9)
(tomcat@9)-->(openjdk)
(tree-sitter) << dep >>
(typescript)
(typescript)-->(node)
(ugrep)
(ugrep)-->(brotli)
(ugrep)-->(lz4)
(ugrep)-->(pcre2)
(ugrep)-->(xz)
(ugrep)-->(zstd)
(unbound) << dep >>
(unbound)-->(libevent)
(unbound)-->(libnghttp2)
(unbound)-->(openssl@3)
(unibilium) << dep >>
(utf8proc) << dep >>
(vde) << dep >>
(vscode-langservers-extracted)
(vscode-langservers-extracted)-->(node)
(webp) << dep >>
(webp)-->(giflib)
(webp)-->(jpeg-turbo)
(webp)-->(libpng)
(webp)-->(libtiff)
(wget)
(wget)-->(gettext)
(wget)-->(libidn2)
(wget)-->(libunistring)
(wget)-->(openssl@3)
(xh)
(xorgproto) << dep >>
(xq)
(xxhash) << dep >>
(xz) << dep >>
(yaml-language-server)
(yaml-language-server)-->(node)
(yarn)
(yq)
(yt-dlp)
(yt-dlp)-->(certifi)
(yt-dlp)-->(python@3.13)
(zlib) << dep >>
(zopfli) << dep >>
(zsh)
(zsh)-->(ncurses)
(zsh)-->(pcre)
(zstd) << dep >>
(zstd)-->(lz4)
(zstd)-->(xz)
@enduml
