@startuml homebrew
skinparam usecase {
    BorderColor DarkSlateGray
    BackgroundColor DarkSeaGreen
    BackgroundColor<< req >> ForestGreen
    BackgroundColor<< dep >> DarkGoldenRod
}
(abseil) << dep >>
(ant)
(ant)-->(cairo)
(ant)-->(fontconfig)
(ant)-->(freetype)
(ant)-->(gettext)
(ant)-->(giflib)
(ant)-->(glib)
(ant)-->(graphite2)
(ant)-->(harfbuzz)
(ant)-->(icu4c)
(ant)-->(jpeg-turbo)
(ant)-->(libpng)
(ant)-->(libtiff)
(ant)-->(libx11)
(ant)-->(libxau)
(ant)-->(libxcb)
(ant)-->(libxdmcp)
(ant)-->(libxext)
(ant)-->(libxrender)
(ant)-->(little-cms2)
(ant)-->(lz4)
(ant)-->(lzo)
(ant)-->(openjdk)
(ant)-->(pcre2)
(ant)-->(pixman)
(ant)-->(xorgproto)
(ant)-->(xz)
(ant)-->(zstd)
(aom) << dep >>
(aom)-->(brotli)
(aom)-->(giflib)
(aom)-->(highway)
(aom)-->(imath)
(aom)-->(jpeg-turbo)
(aom)-->(jpeg-xl)
(aom)-->(libpng)
(aom)-->(libtiff)
(aom)-->(libvmaf)
(aom)-->(little-cms2)
(aom)-->(lz4)
(aom)-->(openexr)
(aom)-->(webp)
(aom)-->(xz)
(aom)-->(zstd)
(apr) << dep >>
(apr-util) << dep >>
(apr-util)-->(apr)
(apr-util)-->(ca-certificates)
(apr-util)-->(openssl@3)
(ares)
(aria2)
(aria2)-->(ca-certificates)
(aria2)-->(gettext)
(aria2)-->(libssh2)
(aria2)-->(openssl@3)
(aria2)-->(readline)
(aria2)-->(sqlite)
(autojump)
(autojump)-->(ca-certificates)
(autojump)-->(mpdecimal)
(autojump)-->(openssl@3)
(autojump)-->(python@3.12)
(autojump)-->(readline)
(autojump)-->(sqlite)
(autojump)-->(xz)
(avro-c) << dep >>
(avro-c)-->(jansson)
(avro-c)-->(snappy)
(avro-c)-->(xz)
(bash)
(bash-completion@2)
(bash-completion@2)-->(bash)
(bash-language-server)
(bash-language-server)-->(brotli)
(bash-language-server)-->(c-ares)
(bash-language-server)-->(ca-certificates)
(bash-language-server)-->(icu4c)
(bash-language-server)-->(libnghttp2)
(bash-language-server)-->(libuv)
(bash-language-server)-->(node)
(bash-language-server)-->(openssl@3)
(bat)
(bat)-->(ca-certificates)
(bat)-->(libgit2)
(bat)-->(libssh2)
(bat)-->(oniguruma)
(bat)-->(openssl@3)
(black)
(black)-->(ca-certificates)
(black)-->(mpdecimal)
(black)-->(openssl@3)
(black)-->(python-attrs)
(black)-->(python-click)
(black)-->(python-idna)
(black)-->(python-packaging)
(black)-->(python-pathspec)
(black)-->(python-platformdirs)
(black)-->(python@3.12)
(black)-->(readline)
(black)-->(sqlite)
(black)-->(xz)
(brotli) << dep >>
(c-ares) << dep >>
(ca-certificates) << dep >>
(cairo) << dep >>
(cairo)-->(fontconfig)
(cairo)-->(freetype)
(cairo)-->(gettext)
(cairo)-->(glib)
(cairo)-->(libpng)
(cairo)-->(libx11)
(cairo)-->(libxau)
(cairo)-->(libxcb)
(cairo)-->(libxdmcp)
(cairo)-->(libxext)
(cairo)-->(libxrender)
(cairo)-->(lzo)
(cairo)-->(pcre2)
(cairo)-->(pixman)
(cairo)-->(xorgproto)
(capstone) << dep >>
(choose-rust)
(clang-format)
(cmake)
(codespell)
(codespell)-->(ca-certificates)
(codespell)-->(mpdecimal)
(codespell)-->(openssl@3)
(codespell)-->(python@3.11)
(codespell)-->(readline)
(codespell)-->(sqlite)
(codespell)-->(xz)
(colima)
(colima)-->(ca-certificates)
(colima)-->(capstone)
(colima)-->(dtc)
(colima)-->(gettext)
(colima)-->(glib)
(colima)-->(gmp)
(colima)-->(gnutls)
(colima)-->(jpeg-turbo)
(colima)-->(libevent)
(colima)-->(libidn2)
(colima)-->(libnghttp2)
(colima)-->(libpng)
(colima)-->(libslirp)
(colima)-->(libssh)
(colima)-->(libtasn1)
(colima)-->(libunistring)
(colima)-->(libusb)
(colima)-->(lima)
(colima)-->(lz4)
(colima)-->(lzo)
(colima)-->(ncurses)
(colima)-->(nettle)
(colima)-->(openssl@3)
(colima)-->(p11-kit)
(colima)-->(pcre2)
(colima)-->(pixman)
(colima)-->(qemu)
(colima)-->(snappy)
(colima)-->(unbound)
(colima)-->(vde)
(colima)-->(xz)
(colima)-->(zstd)
(cpanminus)
(croc)
(curl)
(curl)-->(brotli)
(curl)-->(ca-certificates)
(curl)-->(gettext)
(curl)-->(libidn2)
(curl)-->(libnghttp2)
(curl)-->(libssh2)
(curl)-->(libunistring)
(curl)-->(lz4)
(curl)-->(openldap)
(curl)-->(openssl@3)
(curl)-->(rtmpdump)
(curl)-->(xz)
(curl)-->(zstd)
(curlie)
(delve)
(deno)
(deno)-->(readline)
(deno)-->(sqlite)
(di)
(direnv)
(docker-completion)
(dog)
(dtc) << dep >>
(dufs)
(dust)
(eslint)
(eslint)-->(brotli)
(eslint)-->(c-ares)
(eslint)-->(ca-certificates)
(eslint)-->(icu4c)
(eslint)-->(libnghttp2)
(eslint)-->(libuv)
(eslint)-->(node)
(eslint)-->(openssl@3)
(eza)
(eza)-->(ca-certificates)
(eza)-->(libgit2)
(eza)-->(libssh2)
(eza)-->(openssl@3)
(fd)
(fdupes)
(fdupes)-->(pcre2)
(figlet)
(file-formula)
(file-formula)-->(libmagic)
(flake8)
(flake8)-->(ca-certificates)
(flake8)-->(mpdecimal)
(flake8)-->(openssl@3)
(flake8)-->(python@3.11)
(flake8)-->(readline)
(flake8)-->(sqlite)
(flake8)-->(xz)
(fontconfig) << dep >>
(fontconfig)-->(freetype)
(fontconfig)-->(libpng)
(fossil)
(fossil)-->(ca-certificates)
(fossil)-->(openssl@3)
(freetype) << dep >>
(freetype)-->(libpng)
(fribidi) << dep >>
(fzf)
(gawk)
(gawk)-->(gettext)
(gawk)-->(gmp)
(gawk)-->(mpfr)
(gawk)-->(readline)
(gd) << dep >>
(gd)-->(aom)
(gd)-->(brotli)
(gd)-->(fontconfig)
(gd)-->(freetype)
(gd)-->(giflib)
(gd)-->(highway)
(gd)-->(imath)
(gd)-->(jpeg-turbo)
(gd)-->(jpeg-xl)
(gd)-->(libavif)
(gd)-->(libpng)
(gd)-->(libtiff)
(gd)-->(libvmaf)
(gd)-->(little-cms2)
(gd)-->(lz4)
(gd)-->(openexr)
(gd)-->(webp)
(gd)-->(xz)
(gd)-->(zstd)
(gdk-pixbuf) << dep >>
(gdk-pixbuf)-->(gettext)
(gdk-pixbuf)-->(glib)
(gdk-pixbuf)-->(jpeg-turbo)
(gdk-pixbuf)-->(libpng)
(gdk-pixbuf)-->(libtiff)
(gdk-pixbuf)-->(lz4)
(gdk-pixbuf)-->(pcre2)
(gdk-pixbuf)-->(xz)
(gdk-pixbuf)-->(zstd)
(gettext) << dep >>
(gh)
(giflib) << dep >>
(git)
(git)-->(gettext)
(git)-->(pcre2)
(git-lfs)
(git-secret)
(git-secret)-->(ca-certificates)
(git-secret)-->(gawk)
(git-secret)-->(gettext)
(git-secret)-->(gmp)
(git-secret)-->(gnupg)
(git-secret)-->(gnutls)
(git-secret)-->(libassuan)
(git-secret)-->(libevent)
(git-secret)-->(libgcrypt)
(git-secret)-->(libgpg-error)
(git-secret)-->(libidn2)
(git-secret)-->(libksba)
(git-secret)-->(libnghttp2)
(git-secret)-->(libtasn1)
(git-secret)-->(libunistring)
(git-secret)-->(libusb)
(git-secret)-->(mpfr)
(git-secret)-->(nettle)
(git-secret)-->(npth)
(git-secret)-->(openldap)
(git-secret)-->(openssl@3)
(git-secret)-->(p11-kit)
(git-secret)-->(pinentry)
(git-secret)-->(readline)
(git-secret)-->(unbound)
(git-svn)
(git-svn)-->(apr)
(git-svn)-->(apr-util)
(git-svn)-->(ca-certificates)
(git-svn)-->(gettext)
(git-svn)-->(git)
(git-svn)-->(lz4)
(git-svn)-->(openssl@3)
(git-svn)-->(pcre2)
(git-svn)-->(subversion)
(git-svn)-->(utf8proc)
(glab)
(glib) << dep >>
(glib)-->(gettext)
(glib)-->(pcre2)
(gmp) << dep >>
(gmssl)
(gnu-sed)
(gnu-tar)
(gnupg)
(gnupg)-->(ca-certificates)
(gnupg)-->(gettext)
(gnupg)-->(gmp)
(gnupg)-->(gnutls)
(gnupg)-->(libassuan)
(gnupg)-->(libevent)
(gnupg)-->(libgcrypt)
(gnupg)-->(libgpg-error)
(gnupg)-->(libidn2)
(gnupg)-->(libksba)
(gnupg)-->(libnghttp2)
(gnupg)-->(libtasn1)
(gnupg)-->(libunistring)
(gnupg)-->(libusb)
(gnupg)-->(nettle)
(gnupg)-->(npth)
(gnupg)-->(openldap)
(gnupg)-->(openssl@3)
(gnupg)-->(p11-kit)
(gnupg)-->(pinentry)
(gnupg)-->(readline)
(gnupg)-->(unbound)
(gnutls) << dep >>
(gnutls)-->(ca-certificates)
(gnutls)-->(gettext)
(gnutls)-->(gmp)
(gnutls)-->(libevent)
(gnutls)-->(libidn2)
(gnutls)-->(libnghttp2)
(gnutls)-->(libtasn1)
(gnutls)-->(libunistring)
(gnutls)-->(nettle)
(gnutls)-->(openssl@3)
(gnutls)-->(p11-kit)
(gnutls)-->(unbound)
(go)
(gomodifytags)
(gopls)
(gost)
(gotags)
(gotests)
(gradle)
(gradle)-->(cairo)
(gradle)-->(fontconfig)
(gradle)-->(freetype)
(gradle)-->(gettext)
(gradle)-->(giflib)
(gradle)-->(glib)
(gradle)-->(graphite2)
(gradle)-->(harfbuzz)
(gradle)-->(icu4c)
(gradle)-->(jpeg-turbo)
(gradle)-->(libpng)
(gradle)-->(libtiff)
(gradle)-->(libx11)
(gradle)-->(libxau)
(gradle)-->(libxcb)
(gradle)-->(libxdmcp)
(gradle)-->(libxext)
(gradle)-->(libxrender)
(gradle)-->(little-cms2)
(gradle)-->(lz4)
(gradle)-->(lzo)
(gradle)-->(openjdk)
(gradle)-->(pcre2)
(gradle)-->(pixman)
(gradle)-->(xorgproto)
(gradle)-->(xz)
(gradle)-->(zstd)
(graphite2) << dep >>
(graphviz) << dep >>
(graphviz)-->(aom)
(graphviz)-->(brotli)
(graphviz)-->(cairo)
(graphviz)-->(fontconfig)
(graphviz)-->(freetype)
(graphviz)-->(fribidi)
(graphviz)-->(gd)
(graphviz)-->(gdk-pixbuf)
(graphviz)-->(gettext)
(graphviz)-->(giflib)
(graphviz)-->(glib)
(graphviz)-->(graphite2)
(graphviz)-->(gts)
(graphviz)-->(harfbuzz)
(graphviz)-->(highway)
(graphviz)-->(icu4c)
(graphviz)-->(imath)
(graphviz)-->(jasper)
(graphviz)-->(jpeg-turbo)
(graphviz)-->(jpeg-xl)
(graphviz)-->(libavif)
(graphviz)-->(libpng)
(graphviz)-->(librsvg)
(graphviz)-->(libtiff)
(graphviz)-->(libtool)
(graphviz)-->(libvmaf)
(graphviz)-->(libx11)
(graphviz)-->(libxau)
(graphviz)-->(libxcb)
(graphviz)-->(libxdmcp)
(graphviz)-->(libxext)
(graphviz)-->(libxrender)
(graphviz)-->(little-cms2)
(graphviz)-->(lz4)
(graphviz)-->(lzo)
(graphviz)-->(m4)
(graphviz)-->(netpbm)
(graphviz)-->(openexr)
(graphviz)-->(pango)
(graphviz)-->(pcre2)
(graphviz)-->(pixman)
(graphviz)-->(webp)
(graphviz)-->(xorgproto)
(graphviz)-->(xz)
(graphviz)-->(zstd)
(grpcurl)
(gts) << dep >>
(gts)-->(gettext)
(gts)-->(glib)
(gts)-->(jasper)
(gts)-->(jpeg-turbo)
(gts)-->(libpng)
(gts)-->(libtiff)
(gts)-->(lz4)
(gts)-->(netpbm)
(gts)-->(pcre2)
(gts)-->(xz)
(gts)-->(zstd)
(harelba/q/q)
(harfbuzz) << dep >>
(harfbuzz)-->(cairo)
(harfbuzz)-->(fontconfig)
(harfbuzz)-->(freetype)
(harfbuzz)-->(gettext)
(harfbuzz)-->(glib)
(harfbuzz)-->(graphite2)
(harfbuzz)-->(icu4c)
(harfbuzz)-->(libpng)
(harfbuzz)-->(libx11)
(harfbuzz)-->(libxau)
(harfbuzz)-->(libxcb)
(harfbuzz)-->(libxdmcp)
(harfbuzz)-->(libxext)
(harfbuzz)-->(libxrender)
(harfbuzz)-->(lzo)
(harfbuzz)-->(pcre2)
(harfbuzz)-->(pixman)
(harfbuzz)-->(xorgproto)
(hazelcast/hz/hazelcast)
(hazelcast/hz/hazelcast)-->(cairo)
(hazelcast/hz/hazelcast)-->(fontconfig)
(hazelcast/hz/hazelcast)-->(freetype)
(hazelcast/hz/hazelcast)-->(gettext)
(hazelcast/hz/hazelcast)-->(giflib)
(hazelcast/hz/hazelcast)-->(glib)
(hazelcast/hz/hazelcast)-->(graphite2)
(hazelcast/hz/hazelcast)-->(harfbuzz)
(hazelcast/hz/hazelcast)-->(icu4c)
(hazelcast/hz/hazelcast)-->(jpeg-turbo)
(hazelcast/hz/hazelcast)-->(libpng)
(hazelcast/hz/hazelcast)-->(libtiff)
(hazelcast/hz/hazelcast)-->(libx11)
(hazelcast/hz/hazelcast)-->(libxau)
(hazelcast/hz/hazelcast)-->(libxcb)
(hazelcast/hz/hazelcast)-->(libxdmcp)
(hazelcast/hz/hazelcast)-->(libxext)
(hazelcast/hz/hazelcast)-->(libxrender)
(hazelcast/hz/hazelcast)-->(little-cms2)
(hazelcast/hz/hazelcast)-->(lz4)
(hazelcast/hz/hazelcast)-->(lzo)
(hazelcast/hz/hazelcast)-->(openjdk)
(hazelcast/hz/hazelcast)-->(pcre2)
(hazelcast/hz/hazelcast)-->(pixman)
(hazelcast/hz/hazelcast)-->(xorgproto)
(hazelcast/hz/hazelcast)-->(xz)
(hazelcast/hz/hazelcast)-->(zstd)
(hazelcast/hz/hazelcast-management-center)
(hazelcast/hz/hazelcast-management-center)-->(cairo)
(hazelcast/hz/hazelcast-management-center)-->(fontconfig)
(hazelcast/hz/hazelcast-management-center)-->(freetype)
(hazelcast/hz/hazelcast-management-center)-->(gettext)
(hazelcast/hz/hazelcast-management-center)-->(giflib)
(hazelcast/hz/hazelcast-management-center)-->(glib)
(hazelcast/hz/hazelcast-management-center)-->(graphite2)
(hazelcast/hz/hazelcast-management-center)-->(harfbuzz)
(hazelcast/hz/hazelcast-management-center)-->(icu4c)
(hazelcast/hz/hazelcast-management-center)-->(jpeg-turbo)
(hazelcast/hz/hazelcast-management-center)-->(libpng)
(hazelcast/hz/hazelcast-management-center)-->(libtiff)
(hazelcast/hz/hazelcast-management-center)-->(libx11)
(hazelcast/hz/hazelcast-management-center)-->(libxau)
(hazelcast/hz/hazelcast-management-center)-->(libxcb)
(hazelcast/hz/hazelcast-management-center)-->(libxdmcp)
(hazelcast/hz/hazelcast-management-center)-->(libxext)
(hazelcast/hz/hazelcast-management-center)-->(libxrender)
(hazelcast/hz/hazelcast-management-center)-->(little-cms2)
(hazelcast/hz/hazelcast-management-center)-->(lz4)
(hazelcast/hz/hazelcast-management-center)-->(lzo)
(hazelcast/hz/hazelcast-management-center)-->(openjdk)
(hazelcast/hz/hazelcast-management-center)-->(pcre2)
(hazelcast/hz/hazelcast-management-center)-->(pixman)
(hazelcast/hz/hazelcast-management-center)-->(xorgproto)
(hazelcast/hz/hazelcast-management-center)-->(xz)
(hazelcast/hz/hazelcast-management-center)-->(zstd)
(helm)
(hexyl)
(highway) << dep >>
(htop)
(htop)-->(ncurses)
(httpie)
(httpie)-->(ca-certificates)
(httpie)-->(mpdecimal)
(httpie)-->(openssl@3)
(httpie)-->(pygments)
(httpie)-->(python-certifi)
(httpie)-->(python@3.12)
(httpie)-->(readline)
(httpie)-->(sqlite)
(httpie)-->(xz)
(icu4c) << dep >>
(imath) << dep >>
(iperf3)
(iperf3)-->(ca-certificates)
(iperf3)-->(openssl@3)
(ipython)
(ipython)-->(ca-certificates)
(ipython)-->(mpdecimal)
(ipython)-->(openssl@3)
(ipython)-->(pygments)
(ipython)-->(python@3.12)
(ipython)-->(readline)
(ipython)-->(six)
(ipython)-->(sqlite)
(ipython)-->(xz)
(jansson) << dep >>
(jasper) << dep >>
(jasper)-->(jpeg-turbo)
(jdtls)
(jdtls)-->(ca-certificates)
(jdtls)-->(cairo)
(jdtls)-->(fontconfig)
(jdtls)-->(freetype)
(jdtls)-->(gettext)
(jdtls)-->(giflib)
(jdtls)-->(glib)
(jdtls)-->(graphite2)
(jdtls)-->(harfbuzz)
(jdtls)-->(icu4c)
(jdtls)-->(jpeg-turbo)
(jdtls)-->(libpng)
(jdtls)-->(libtiff)
(jdtls)-->(libx11)
(jdtls)-->(libxau)
(jdtls)-->(libxcb)
(jdtls)-->(libxdmcp)
(jdtls)-->(libxext)
(jdtls)-->(libxrender)
(jdtls)-->(little-cms2)
(jdtls)-->(lz4)
(jdtls)-->(lzo)
(jdtls)-->(mpdecimal)
(jdtls)-->(openjdk)
(jdtls)-->(openssl@3)
(jdtls)-->(pcre2)
(jdtls)-->(pixman)
(jdtls)-->(python@3.12)
(jdtls)-->(readline)
(jdtls)-->(sqlite)
(jdtls)-->(xorgproto)
(jdtls)-->(xz)
(jdtls)-->(zstd)
(jpeg-turbo) << dep >>
(jpeg-xl) << dep >>
(jpeg-xl)-->(brotli)
(jpeg-xl)-->(giflib)
(jpeg-xl)-->(highway)
(jpeg-xl)-->(imath)
(jpeg-xl)-->(jpeg-turbo)
(jpeg-xl)-->(libpng)
(jpeg-xl)-->(libtiff)
(jpeg-xl)-->(little-cms2)
(jpeg-xl)-->(lz4)
(jpeg-xl)-->(openexr)
(jpeg-xl)-->(webp)
(jpeg-xl)-->(xz)
(jpeg-xl)-->(zstd)
(jq)
(jq)-->(oniguruma)
(jsoncpp) << dep >>
(kafka)
(kafka)-->(ca-certificates)
(kafka)-->(cairo)
(kafka)-->(fontconfig)
(kafka)-->(freetype)
(kafka)-->(gettext)
(kafka)-->(giflib)
(kafka)-->(glib)
(kafka)-->(graphite2)
(kafka)-->(harfbuzz)
(kafka)-->(icu4c)
(kafka)-->(jpeg-turbo)
(kafka)-->(libpng)
(kafka)-->(libtiff)
(kafka)-->(libx11)
(kafka)-->(libxau)
(kafka)-->(libxcb)
(kafka)-->(libxdmcp)
(kafka)-->(libxext)
(kafka)-->(libxrender)
(kafka)-->(little-cms2)
(kafka)-->(lz4)
(kafka)-->(lzo)
(kafka)-->(openjdk)
(kafka)-->(openssl@3)
(kafka)-->(pcre2)
(kafka)-->(pixman)
(kafka)-->(xorgproto)
(kafka)-->(xz)
(kafka)-->(zookeeper)
(kafka)-->(zstd)
(kcat)
(kcat)-->(avro-c)
(kcat)-->(ca-certificates)
(kcat)-->(jansson)
(kcat)-->(librdkafka)
(kcat)-->(libserdes)
(kcat)-->(lz4)
(kcat)-->(lzlib)
(kcat)-->(openssl@3)
(kcat)-->(snappy)
(kcat)-->(xz)
(kcat)-->(yajl)
(kcat)-->(zstd)
(lazygit)
(libassuan) << dep >>
(libassuan)-->(gettext)
(libassuan)-->(libgpg-error)
(libavif) << dep >>
(libavif)-->(aom)
(libavif)-->(brotli)
(libavif)-->(giflib)
(libavif)-->(highway)
(libavif)-->(imath)
(libavif)-->(jpeg-turbo)
(libavif)-->(jpeg-xl)
(libavif)-->(libpng)
(libavif)-->(libtiff)
(libavif)-->(libvmaf)
(libavif)-->(little-cms2)
(libavif)-->(lz4)
(libavif)-->(openexr)
(libavif)-->(webp)
(libavif)-->(xz)
(libavif)-->(zstd)
(libevent) << dep >>
(libevent)-->(ca-certificates)
(libevent)-->(openssl@3)
(libgcrypt) << dep >>
(libgcrypt)-->(gettext)
(libgcrypt)-->(libgpg-error)
(libgit2) << dep >>
(libgit2)-->(ca-certificates)
(libgit2)-->(libssh2)
(libgit2)-->(openssl@3)
(libgpg-error) << dep >>
(libgpg-error)-->(gettext)
(libidn2) << dep >>
(libidn2)-->(gettext)
(libidn2)-->(libunistring)
(libksba) << dep >>
(libksba)-->(gettext)
(libksba)-->(libgpg-error)
(liblinear) << dep >>
(libmagic) << dep >>
(libnghttp2) << dep >>
(libpng) << dep >>
(librdkafka) << dep >>
(librdkafka)-->(ca-certificates)
(librdkafka)-->(lz4)
(librdkafka)-->(lzlib)
(librdkafka)-->(openssl@3)
(librdkafka)-->(xz)
(librdkafka)-->(zstd)
(librsvg) << dep >>
(librsvg)-->(cairo)
(librsvg)-->(fontconfig)
(librsvg)-->(freetype)
(librsvg)-->(fribidi)
(librsvg)-->(gdk-pixbuf)
(librsvg)-->(gettext)
(librsvg)-->(glib)
(librsvg)-->(graphite2)
(librsvg)-->(harfbuzz)
(librsvg)-->(icu4c)
(librsvg)-->(jpeg-turbo)
(librsvg)-->(libpng)
(librsvg)-->(libtiff)
(librsvg)-->(libx11)
(librsvg)-->(libxau)
(librsvg)-->(libxcb)
(librsvg)-->(libxdmcp)
(librsvg)-->(libxext)
(librsvg)-->(libxrender)
(librsvg)-->(lz4)
(librsvg)-->(lzo)
(librsvg)-->(pango)
(librsvg)-->(pcre2)
(librsvg)-->(pixman)
(librsvg)-->(xorgproto)
(librsvg)-->(xz)
(librsvg)-->(zstd)
(libserdes) << dep >>
(libserdes)-->(avro-c)
(libserdes)-->(jansson)
(libserdes)-->(snappy)
(libserdes)-->(xz)
(libslirp) << dep >>
(libslirp)-->(gettext)
(libslirp)-->(glib)
(libslirp)-->(pcre2)
(libssh) << dep >>
(libssh)-->(ca-certificates)
(libssh)-->(openssl@3)
(libssh2) << dep >>
(libssh2)-->(ca-certificates)
(libssh2)-->(openssl@3)
(libtasn1) << dep >>
(libtermkey) << dep >>
(libtermkey)-->(unibilium)
(libtiff) << dep >>
(libtiff)-->(jpeg-turbo)
(libtiff)-->(lz4)
(libtiff)-->(xz)
(libtiff)-->(zstd)
(libtool) << dep >>
(libtool)-->(m4)
(libunistring) << dep >>
(libusb) << dep >>
(libuv) << dep >>
(libvmaf) << dep >>
(libvterm) << dep >>
(libx11) << dep >>
(libx11)-->(libxau)
(libx11)-->(libxcb)
(libx11)-->(libxdmcp)
(libx11)-->(xorgproto)
(libxau) << dep >>
(libxau)-->(xorgproto)
(libxcb) << dep >>
(libxcb)-->(libxau)
(libxcb)-->(libxdmcp)
(libxcb)-->(xorgproto)
(libxdmcp) << dep >>
(libxdmcp)-->(xorgproto)
(libxext) << dep >>
(libxext)-->(libx11)
(libxext)-->(libxau)
(libxext)-->(libxcb)
(libxext)-->(libxdmcp)
(libxext)-->(xorgproto)
(libxrender) << dep >>
(libxrender)-->(libx11)
(libxrender)-->(libxau)
(libxrender)-->(libxcb)
(libxrender)-->(libxdmcp)
(libxrender)-->(xorgproto)
(libyaml) << dep >>
(lima) << dep >>
(lima)-->(ca-certificates)
(lima)-->(capstone)
(lima)-->(dtc)
(lima)-->(gettext)
(lima)-->(glib)
(lima)-->(gmp)
(lima)-->(gnutls)
(lima)-->(jpeg-turbo)
(lima)-->(libevent)
(lima)-->(libidn2)
(lima)-->(libnghttp2)
(lima)-->(libpng)
(lima)-->(libslirp)
(lima)-->(libssh)
(lima)-->(libtasn1)
(lima)-->(libunistring)
(lima)-->(libusb)
(lima)-->(lz4)
(lima)-->(lzo)
(lima)-->(ncurses)
(lima)-->(nettle)
(lima)-->(openssl@3)
(lima)-->(p11-kit)
(lima)-->(pcre2)
(lima)-->(pixman)
(lima)-->(qemu)
(lima)-->(snappy)
(lima)-->(unbound)
(lima)-->(vde)
(lima)-->(xz)
(lima)-->(zstd)
(little-cms2) << dep >>
(little-cms2)-->(jpeg-turbo)
(little-cms2)-->(libtiff)
(little-cms2)-->(lz4)
(little-cms2)-->(xz)
(little-cms2)-->(zstd)
(llvm) << dep >>
(llvm)-->(ca-certificates)
(llvm)-->(lz4)
(llvm)-->(mpdecimal)
(llvm)-->(openssl@3)
(llvm)-->(python@3.12)
(llvm)-->(readline)
(llvm)-->(sqlite)
(llvm)-->(xz)
(llvm)-->(z3)
(llvm)-->(zstd)
(lrzsz)
(lua)
(lua-language-server)
(luajit) << dep >>
(luv) << dep >>
(luv)-->(libuv)
(lz4) << dep >>
(lzlib) << dep >>
(lzo) << dep >>
(m4) << dep >>
(marksman)
(mas)
(maven)
(maven)-->(cairo)
(maven)-->(fontconfig)
(maven)-->(freetype)
(maven)-->(gettext)
(maven)-->(giflib)
(maven)-->(glib)
(maven)-->(graphite2)
(maven)-->(harfbuzz)
(maven)-->(icu4c)
(maven)-->(jpeg-turbo)
(maven)-->(libpng)
(maven)-->(libtiff)
(maven)-->(libx11)
(maven)-->(libxau)
(maven)-->(libxcb)
(maven)-->(libxdmcp)
(maven)-->(libxext)
(maven)-->(libxrender)
(maven)-->(little-cms2)
(maven)-->(lz4)
(maven)-->(lzo)
(maven)-->(openjdk)
(maven)-->(pcre2)
(maven)-->(pixman)
(maven)-->(xorgproto)
(maven)-->(xz)
(maven)-->(zstd)
(miniserve)
(mkcert)
(mongodb/brew/mongodb-community)
(mongodb/brew/mongodb-community)-->(brotli)
(mongodb/brew/mongodb-community)-->(c-ares)
(mongodb/brew/mongodb-community)-->(ca-certificates)
(mongodb/brew/mongodb-community)-->(icu4c)
(mongodb/brew/mongodb-community)-->(libnghttp2)
(mongodb/brew/mongodb-community)-->(libuv)
(mongodb/brew/mongodb-community)-->(mongodb/brew/mongodb-database-tools)
(mongodb/brew/mongodb-community)-->(mongosh)
(mongodb/brew/mongodb-community)-->(node)
(mongodb/brew/mongodb-community)-->(openssl@3)
(mongodb/brew/mongodb-database-tools) << req >>
(mongosh) << dep >>
(mongosh)-->(brotli)
(mongosh)-->(c-ares)
(mongosh)-->(ca-certificates)
(mongosh)-->(icu4c)
(mongosh)-->(libnghttp2)
(mongosh)-->(libuv)
(mongosh)-->(node)
(mongosh)-->(openssl@3)
(moonfruit/tap/colorsvn)
(moonfruit/tap/ethr)
(moonfruit/tap/geo)
(moonfruit/tap/gost@3)
(moonfruit/tap/impl)
(moonfruit/tap/impl)-->(go)
(moonfruit/tap/macos-totp-cli)
(moonfruit/tap/sshpass)
(moonfruit/tap/ugrep-indexer)
(moonfruit/tap/ugrep-indexer)-->(brotli)
(moonfruit/tap/ugrep-indexer)-->(lz4)
(moonfruit/tap/ugrep-indexer)-->(xz)
(moonfruit/tap/ugrep-indexer)-->(zstd)
(moonfruit/tap/uutils-selected)
(moonfruit/tap/wlp-webprofile8)
(moonfruit/tap/wlp-webprofile8)-->(cairo)
(moonfruit/tap/wlp-webprofile8)-->(fontconfig)
(moonfruit/tap/wlp-webprofile8)-->(freetype)
(moonfruit/tap/wlp-webprofile8)-->(gettext)
(moonfruit/tap/wlp-webprofile8)-->(giflib)
(moonfruit/tap/wlp-webprofile8)-->(glib)
(moonfruit/tap/wlp-webprofile8)-->(graphite2)
(moonfruit/tap/wlp-webprofile8)-->(harfbuzz)
(moonfruit/tap/wlp-webprofile8)-->(icu4c)
(moonfruit/tap/wlp-webprofile8)-->(jpeg-turbo)
(moonfruit/tap/wlp-webprofile8)-->(libpng)
(moonfruit/tap/wlp-webprofile8)-->(libtiff)
(moonfruit/tap/wlp-webprofile8)-->(libx11)
(moonfruit/tap/wlp-webprofile8)-->(libxau)
(moonfruit/tap/wlp-webprofile8)-->(libxcb)
(moonfruit/tap/wlp-webprofile8)-->(libxdmcp)
(moonfruit/tap/wlp-webprofile8)-->(libxext)
(moonfruit/tap/wlp-webprofile8)-->(libxrender)
(moonfruit/tap/wlp-webprofile8)-->(little-cms2)
(moonfruit/tap/wlp-webprofile8)-->(lz4)
(moonfruit/tap/wlp-webprofile8)-->(lzo)
(moonfruit/tap/wlp-webprofile8)-->(openjdk)
(moonfruit/tap/wlp-webprofile8)-->(pcre2)
(moonfruit/tap/wlp-webprofile8)-->(pixman)
(moonfruit/tap/wlp-webprofile8)-->(xorgproto)
(moonfruit/tap/wlp-webprofile8)-->(xz)
(moonfruit/tap/wlp-webprofile8)-->(zstd)
(mosh)
(mosh)-->(abseil)
(mosh)-->(jsoncpp)
(mosh)-->(protobuf)
(mpdecimal) << dep >>
(mpfr) << dep >>
(mpfr)-->(gmp)
(msgpack) << dep >>
(ncdu)
(ncdu)-->(ncurses)
(ncruces/tap/zenity)
(ncurses) << dep >>
(neovide)
(neovide)-->(gettext)
(neovide)-->(libtermkey)
(neovide)-->(libuv)
(neovide)-->(libvterm)
(neovide)-->(luajit)
(neovide)-->(luv)
(neovide)-->(msgpack)
(neovide)-->(neovim)
(neovide)-->(tree-sitter)
(neovide)-->(unibilium)
(neovim)
(neovim)-->(gettext)
(neovim)-->(libtermkey)
(neovim)-->(libuv)
(neovim)-->(libvterm)
(neovim)-->(luajit)
(neovim)-->(luv)
(neovim)-->(msgpack)
(neovim)-->(tree-sitter)
(neovim)-->(unibilium)
(netpbm) << dep >>
(netpbm)-->(jasper)
(netpbm)-->(jpeg-turbo)
(netpbm)-->(libpng)
(netpbm)-->(libtiff)
(netpbm)-->(lz4)
(netpbm)-->(xz)
(netpbm)-->(zstd)
(nettle) << dep >>
(nettle)-->(gmp)
(nmap)
(nmap)-->(ca-certificates)
(nmap)-->(liblinear)
(nmap)-->(libssh2)
(nmap)-->(lua)
(nmap)-->(openssl@3)
(nmap)-->(pcre)
(node)
(node)-->(brotli)
(node)-->(c-ares)
(node)-->(ca-certificates)
(node)-->(icu4c)
(node)-->(libnghttp2)
(node)-->(libuv)
(node)-->(openssl@3)
(node@16) << req >>
(node@16)-->(brotli)
(node@16)-->(c-ares)
(node@16)-->(ca-certificates)
(node@16)-->(icu4c)
(node@16)-->(libnghttp2)
(node@16)-->(libuv)
(node@16)-->(openssl@3)
(npth) << dep >>
(oniguruma) << dep >>
(opencc)
(openexr) << dep >>
(openexr)-->(imath)
(openjdk)
(openjdk)-->(cairo)
(openjdk)-->(fontconfig)
(openjdk)-->(freetype)
(openjdk)-->(gettext)
(openjdk)-->(giflib)
(openjdk)-->(glib)
(openjdk)-->(graphite2)
(openjdk)-->(harfbuzz)
(openjdk)-->(icu4c)
(openjdk)-->(jpeg-turbo)
(openjdk)-->(libpng)
(openjdk)-->(libtiff)
(openjdk)-->(libx11)
(openjdk)-->(libxau)
(openjdk)-->(libxcb)
(openjdk)-->(libxdmcp)
(openjdk)-->(libxext)
(openjdk)-->(libxrender)
(openjdk)-->(little-cms2)
(openjdk)-->(lz4)
(openjdk)-->(lzo)
(openjdk)-->(pcre2)
(openjdk)-->(pixman)
(openjdk)-->(xorgproto)
(openjdk)-->(xz)
(openjdk)-->(zstd)
(openjdk@11)
(openjdk@11)-->(cairo)
(openjdk@11)-->(fontconfig)
(openjdk@11)-->(freetype)
(openjdk@11)-->(gettext)
(openjdk@11)-->(giflib)
(openjdk@11)-->(glib)
(openjdk@11)-->(graphite2)
(openjdk@11)-->(harfbuzz)
(openjdk@11)-->(icu4c)
(openjdk@11)-->(jpeg-turbo)
(openjdk@11)-->(libpng)
(openjdk@11)-->(libtiff)
(openjdk@11)-->(libx11)
(openjdk@11)-->(libxau)
(openjdk@11)-->(libxcb)
(openjdk@11)-->(libxdmcp)
(openjdk@11)-->(libxext)
(openjdk@11)-->(libxrender)
(openjdk@11)-->(little-cms2)
(openjdk@11)-->(lz4)
(openjdk@11)-->(lzo)
(openjdk@11)-->(pcre2)
(openjdk@11)-->(pixman)
(openjdk@11)-->(xorgproto)
(openjdk@11)-->(xz)
(openjdk@11)-->(zstd)
(openjdk@17)
(openjdk@17)-->(cairo)
(openjdk@17)-->(fontconfig)
(openjdk@17)-->(freetype)
(openjdk@17)-->(gettext)
(openjdk@17)-->(giflib)
(openjdk@17)-->(glib)
(openjdk@17)-->(graphite2)
(openjdk@17)-->(harfbuzz)
(openjdk@17)-->(icu4c)
(openjdk@17)-->(jpeg-turbo)
(openjdk@17)-->(libpng)
(openjdk@17)-->(libtiff)
(openjdk@17)-->(libx11)
(openjdk@17)-->(libxau)
(openjdk@17)-->(libxcb)
(openjdk@17)-->(libxdmcp)
(openjdk@17)-->(libxext)
(openjdk@17)-->(libxrender)
(openjdk@17)-->(little-cms2)
(openjdk@17)-->(lz4)
(openjdk@17)-->(lzo)
(openjdk@17)-->(pcre2)
(openjdk@17)-->(pixman)
(openjdk@17)-->(xorgproto)
(openjdk@17)-->(xz)
(openjdk@17)-->(zstd)
(openldap) << dep >>
(openldap)-->(ca-certificates)
(openldap)-->(openssl@3)
(openssl@3) << dep >>
(openssl@3)-->(ca-certificates)
(p11-kit) << dep >>
(p11-kit)-->(ca-certificates)
(p11-kit)-->(libtasn1)
(p7zip)
(pandoc)
(pango) << dep >>
(pango)-->(cairo)
(pango)-->(fontconfig)
(pango)-->(freetype)
(pango)-->(fribidi)
(pango)-->(gettext)
(pango)-->(glib)
(pango)-->(graphite2)
(pango)-->(harfbuzz)
(pango)-->(icu4c)
(pango)-->(libpng)
(pango)-->(libx11)
(pango)-->(libxau)
(pango)-->(libxcb)
(pango)-->(libxdmcp)
(pango)-->(libxext)
(pango)-->(libxrender)
(pango)-->(lzo)
(pango)-->(pcre2)
(pango)-->(pixman)
(pango)-->(xorgproto)
(parallel)
(pcre) << dep >>
(pcre2) << dep >>
(pigz)
(pigz)-->(zopfli)
(pinentry) << dep >>
(pinentry)-->(gettext)
(pinentry)-->(libassuan)
(pinentry)-->(libgpg-error)
(pinentry-mac)
(pinentry-mac)-->(gettext)
(pinentry-mac)-->(libassuan)
(pinentry-mac)-->(libgpg-error)
(pipgrip)
(pipgrip)-->(ca-certificates)
(pipgrip)-->(mpdecimal)
(pipgrip)-->(openssl@3)
(pipgrip)-->(python-click)
(pipgrip)-->(python-packaging)
(pipgrip)-->(python-setuptools)
(pipgrip)-->(python@3.12)
(pipgrip)-->(readline)
(pipgrip)-->(six)
(pipgrip)-->(sqlite)
(pipgrip)-->(xz)
(pixman) << dep >>
(pkg-config) << dep >>
(plantuml)
(plantuml)-->(aom)
(plantuml)-->(brotli)
(plantuml)-->(cairo)
(plantuml)-->(fontconfig)
(plantuml)-->(freetype)
(plantuml)-->(fribidi)
(plantuml)-->(gd)
(plantuml)-->(gdk-pixbuf)
(plantuml)-->(gettext)
(plantuml)-->(giflib)
(plantuml)-->(glib)
(plantuml)-->(graphite2)
(plantuml)-->(graphviz)
(plantuml)-->(gts)
(plantuml)-->(harfbuzz)
(plantuml)-->(highway)
(plantuml)-->(icu4c)
(plantuml)-->(imath)
(plantuml)-->(jasper)
(plantuml)-->(jpeg-turbo)
(plantuml)-->(jpeg-xl)
(plantuml)-->(libavif)
(plantuml)-->(libpng)
(plantuml)-->(librsvg)
(plantuml)-->(libtiff)
(plantuml)-->(libtool)
(plantuml)-->(libvmaf)
(plantuml)-->(libx11)
(plantuml)-->(libxau)
(plantuml)-->(libxcb)
(plantuml)-->(libxdmcp)
(plantuml)-->(libxext)
(plantuml)-->(libxrender)
(plantuml)-->(little-cms2)
(plantuml)-->(lz4)
(plantuml)-->(lzo)
(plantuml)-->(m4)
(plantuml)-->(netpbm)
(plantuml)-->(openexr)
(plantuml)-->(openjdk)
(plantuml)-->(pango)
(plantuml)-->(pcre2)
(plantuml)-->(pixman)
(plantuml)-->(webp)
(plantuml)-->(xorgproto)
(plantuml)-->(xz)
(plantuml)-->(zstd)
(popt) << dep >>
(prettier)
(prettier)-->(brotli)
(prettier)-->(c-ares)
(prettier)-->(ca-certificates)
(prettier)-->(icu4c)
(prettier)-->(libnghttp2)
(prettier)-->(libuv)
(prettier)-->(node)
(prettier)-->(openssl@3)
(protobuf)
(protobuf)-->(abseil)
(protobuf)-->(jsoncpp)
(proxychains-ng)
(pstree)
(pup)
(pv)
(pygments) << dep >>
(pyright)
(pyright)-->(brotli)
(pyright)-->(c-ares)
(pyright)-->(ca-certificates)
(pyright)-->(icu4c)
(pyright)-->(libnghttp2)
(pyright)-->(libuv)
(pyright)-->(node)
(pyright)-->(openssl@3)
(python-attrs) << dep >>
(python-certifi) << dep >>
(python-certifi)-->(ca-certificates)
(python-click) << dep >>
(python-idna) << dep >>
(python-mutagen) << dep >>
(python-packaging) << dep >>
(python-pathspec) << dep >>
(python-platformdirs) << dep >>
(python-setuptools) << dep >>
(python@3.11) << req >>
(python@3.11)-->(ca-certificates)
(python@3.11)-->(mpdecimal)
(python@3.11)-->(openssl@3)
(python@3.11)-->(readline)
(python@3.11)-->(sqlite)
(python@3.11)-->(xz)
(python@3.12) << dep >>
(python@3.12)-->(ca-certificates)
(python@3.12)-->(mpdecimal)
(python@3.12)-->(openssl@3)
(python@3.12)-->(readline)
(python@3.12)-->(sqlite)
(python@3.12)-->(xz)
(qemu) << dep >>
(qemu)-->(ca-certificates)
(qemu)-->(capstone)
(qemu)-->(dtc)
(qemu)-->(gettext)
(qemu)-->(glib)
(qemu)-->(gmp)
(qemu)-->(gnutls)
(qemu)-->(jpeg-turbo)
(qemu)-->(libevent)
(qemu)-->(libidn2)
(qemu)-->(libnghttp2)
(qemu)-->(libpng)
(qemu)-->(libslirp)
(qemu)-->(libssh)
(qemu)-->(libtasn1)
(qemu)-->(libunistring)
(qemu)-->(libusb)
(qemu)-->(lz4)
(qemu)-->(lzo)
(qemu)-->(ncurses)
(qemu)-->(nettle)
(qemu)-->(openssl@3)
(qemu)-->(p11-kit)
(qemu)-->(pcre2)
(qemu)-->(pixman)
(qemu)-->(snappy)
(qemu)-->(unbound)
(qemu)-->(vde)
(qemu)-->(xz)
(qemu)-->(zstd)
(qsv)
(rcs)
(readline) << dep >>
(redis)
(redis)-->(ca-certificates)
(redis)-->(openssl@3)
(ripgrep)
(ripgrep)-->(pcre2)
(rlwrap)
(rlwrap)-->(readline)
(rsync)
(rsync)-->(ca-certificates)
(rsync)-->(lz4)
(rsync)-->(openssl@3)
(rsync)-->(popt)
(rsync)-->(xxhash)
(rsync)-->(xz)
(rsync)-->(zstd)
(rtmpdump) << dep >>
(rtmpdump)-->(ca-certificates)
(rtmpdump)-->(openssl@3)
(ruby)
(ruby)-->(ca-certificates)
(ruby)-->(libyaml)
(ruby)-->(openssl@3)
(ruby)-->(readline)
(rust)
(rust)-->(ca-certificates)
(rust)-->(libgit2)
(rust)-->(libssh2)
(rust)-->(llvm)
(rust)-->(lz4)
(rust)-->(mpdecimal)
(rust)-->(openssl@3)
(rust)-->(pkg-config)
(rust)-->(python@3.12)
(rust)-->(readline)
(rust)-->(sqlite)
(rust)-->(xz)
(rust)-->(z3)
(rust)-->(zstd)
(sd)
(shellcheck)
(shfmt)
(sing-box)
(six) << dep >>
(snappy) << dep >>
(sqlite) << dep >>
(sqlite)-->(readline)
(staticcheck)
(staticcheck)-->(go)
(stylua)
(subversion)
(subversion)-->(apr)
(subversion)-->(apr-util)
(subversion)-->(ca-certificates)
(subversion)-->(gettext)
(subversion)-->(lz4)
(subversion)-->(openssl@3)
(subversion)-->(utf8proc)
(swift-format)
(tailwindcss-language-server)
(tailwindcss-language-server)-->(brotli)
(tailwindcss-language-server)-->(c-ares)
(tailwindcss-language-server)-->(ca-certificates)
(tailwindcss-language-server)-->(icu4c)
(tailwindcss-language-server)-->(libnghttp2)
(tailwindcss-language-server)-->(libuv)
(tailwindcss-language-server)-->(node)
(tailwindcss-language-server)-->(openssl@3)
(taplo)
(tcping)
(testssl)
(testssl)-->(ca-certificates)
(testssl)-->(openssl@3)
(tmux)
(tmux)-->(ca-certificates)
(tmux)-->(libevent)
(tmux)-->(ncurses)
(tmux)-->(openssl@3)
(tmux)-->(utf8proc)
(tokei)
(tomcat-native)
(tomcat-native)-->(apr)
(tomcat-native)-->(ca-certificates)
(tomcat-native)-->(cairo)
(tomcat-native)-->(fontconfig)
(tomcat-native)-->(freetype)
(tomcat-native)-->(gettext)
(tomcat-native)-->(giflib)
(tomcat-native)-->(glib)
(tomcat-native)-->(graphite2)
(tomcat-native)-->(harfbuzz)
(tomcat-native)-->(icu4c)
(tomcat-native)-->(jpeg-turbo)
(tomcat-native)-->(libpng)
(tomcat-native)-->(libtiff)
(tomcat-native)-->(libx11)
(tomcat-native)-->(libxau)
(tomcat-native)-->(libxcb)
(tomcat-native)-->(libxdmcp)
(tomcat-native)-->(libxext)
(tomcat-native)-->(libxrender)
(tomcat-native)-->(little-cms2)
(tomcat-native)-->(lz4)
(tomcat-native)-->(lzo)
(tomcat-native)-->(openjdk)
(tomcat-native)-->(openssl@3)
(tomcat-native)-->(pcre2)
(tomcat-native)-->(pixman)
(tomcat-native)-->(xorgproto)
(tomcat-native)-->(xz)
(tomcat-native)-->(zstd)
(tomcat@9)
(tomcat@9)-->(cairo)
(tomcat@9)-->(fontconfig)
(tomcat@9)-->(freetype)
(tomcat@9)-->(gettext)
(tomcat@9)-->(giflib)
(tomcat@9)-->(glib)
(tomcat@9)-->(graphite2)
(tomcat@9)-->(harfbuzz)
(tomcat@9)-->(icu4c)
(tomcat@9)-->(jpeg-turbo)
(tomcat@9)-->(libpng)
(tomcat@9)-->(libtiff)
(tomcat@9)-->(libx11)
(tomcat@9)-->(libxau)
(tomcat@9)-->(libxcb)
(tomcat@9)-->(libxdmcp)
(tomcat@9)-->(libxext)
(tomcat@9)-->(libxrender)
(tomcat@9)-->(little-cms2)
(tomcat@9)-->(lz4)
(tomcat@9)-->(lzo)
(tomcat@9)-->(openjdk)
(tomcat@9)-->(pcre2)
(tomcat@9)-->(pixman)
(tomcat@9)-->(xorgproto)
(tomcat@9)-->(xz)
(tomcat@9)-->(zstd)
(tree-sitter) << dep >>
(typescript)
(typescript)-->(brotli)
(typescript)-->(c-ares)
(typescript)-->(ca-certificates)
(typescript)-->(icu4c)
(typescript)-->(libnghttp2)
(typescript)-->(libuv)
(typescript)-->(node)
(typescript)-->(openssl@3)
(typescript-language-server)
(typescript-language-server)-->(brotli)
(typescript-language-server)-->(c-ares)
(typescript-language-server)-->(ca-certificates)
(typescript-language-server)-->(icu4c)
(typescript-language-server)-->(libnghttp2)
(typescript-language-server)-->(libuv)
(typescript-language-server)-->(node)
(typescript-language-server)-->(openssl@3)
(typescript-language-server)-->(typescript)
(ugrep)
(ugrep)-->(pcre2)
(ugrep)-->(xz)
(unbound) << dep >>
(unbound)-->(ca-certificates)
(unbound)-->(libevent)
(unbound)-->(libnghttp2)
(unbound)-->(openssl@3)
(unibilium) << dep >>
(utf8proc) << dep >>
(vale)
(vde) << dep >>
(vscode-langservers-extracted)
(vscode-langservers-extracted)-->(brotli)
(vscode-langservers-extracted)-->(c-ares)
(vscode-langservers-extracted)-->(ca-certificates)
(vscode-langservers-extracted)-->(icu4c)
(vscode-langservers-extracted)-->(libnghttp2)
(vscode-langservers-extracted)-->(libuv)
(vscode-langservers-extracted)-->(node)
(vscode-langservers-extracted)-->(openssl@3)
(webp) << dep >>
(webp)-->(giflib)
(webp)-->(jpeg-turbo)
(webp)-->(libpng)
(webp)-->(libtiff)
(webp)-->(lz4)
(webp)-->(xz)
(webp)-->(zstd)
(wget)
(wget)-->(ca-certificates)
(wget)-->(gettext)
(wget)-->(libidn2)
(wget)-->(libunistring)
(wget)-->(openssl@3)
(xh)
(xorgproto) << dep >>
(xq)
(xxhash) << dep >>
(xz) << dep >>
(yajl) << dep >>
(yaml-language-server)
(yaml-language-server)-->(brotli)
(yaml-language-server)-->(c-ares)
(yaml-language-server)-->(ca-certificates)
(yaml-language-server)-->(icu4c)
(yaml-language-server)-->(libnghttp2)
(yaml-language-server)-->(libuv)
(yaml-language-server)-->(node)
(yaml-language-server)-->(openssl@3)
(yarn)
(yq)
(yt-dlp)
(yt-dlp)-->(ca-certificates)
(yt-dlp)-->(mpdecimal)
(yt-dlp)-->(openssl@3)
(yt-dlp)-->(python-certifi)
(yt-dlp)-->(python-mutagen)
(yt-dlp)-->(python@3.12)
(yt-dlp)-->(readline)
(yt-dlp)-->(sqlite)
(yt-dlp)-->(xz)
(z3) << dep >>
(zookeeper) << dep >>
(zookeeper)-->(ca-certificates)
(zookeeper)-->(cairo)
(zookeeper)-->(fontconfig)
(zookeeper)-->(freetype)
(zookeeper)-->(gettext)
(zookeeper)-->(giflib)
(zookeeper)-->(glib)
(zookeeper)-->(graphite2)
(zookeeper)-->(harfbuzz)
(zookeeper)-->(icu4c)
(zookeeper)-->(jpeg-turbo)
(zookeeper)-->(libpng)
(zookeeper)-->(libtiff)
(zookeeper)-->(libx11)
(zookeeper)-->(libxau)
(zookeeper)-->(libxcb)
(zookeeper)-->(libxdmcp)
(zookeeper)-->(libxext)
(zookeeper)-->(libxrender)
(zookeeper)-->(little-cms2)
(zookeeper)-->(lz4)
(zookeeper)-->(lzo)
(zookeeper)-->(openjdk)
(zookeeper)-->(openssl@3)
(zookeeper)-->(pcre2)
(zookeeper)-->(pixman)
(zookeeper)-->(xorgproto)
(zookeeper)-->(xz)
(zookeeper)-->(zstd)
(zopfli) << dep >>
(zsh)
(zsh)-->(ncurses)
(zsh)-->(pcre)
(zstd) << dep >>
(zstd)-->(lz4)
(zstd)-->(xz)
@enduml
