@startuml 李家
(李文华)-->(李宏利)
(李文华)-->(李宏毅)

(李宏利)-->(李林州)
(李宏利)-[dashed]->(李建通): 私生子
(李林州)-->(李建通)
(李建通)-->(李乐乐)
(李建通)-->(李浩)

(李宏毅)-->(李林俊)
(李林二) <<夭折>>
(李宏毅)-->(李林二)
(李林三) <<庶出>>
(李宏毅)-->(李林三)

(李林俊)-->(李建唐)
(李林俊)-->(李建成)
(李圆) <<女>>
(李林俊)-[dashed]->(李圆): 收养
(李建娟) <<女>>
(李林三)-->(李建娟)

(李建唐)-->(李惠普)
(李建成)-->(李梦)
(李建娟)-->(孙霜)

(孙霜)<->(向斌)
(孙霜)-->(向晓涵)
(向斌)-->(向晓涵)

(苏秀敏) <<女>>
(向红才)<->(苏秀敏)
(向红才)-->(向斌)
(向红才)-[dashed]->(李圆): 收养
(苏秀敏)-->(向斌)
(苏秀敏)-[dashed]->(李圆): 收养

(李建娟)<->(孙坤)
(孙坤)-->(孙霜)

(孙父)-->(孙乾)
(孙父)-->(孙坤)

(孙乾)-[dotted]->(向斌): 手下

(安树文)<-[dotted]->(李建成): 兄弟
(安树文)-[dotted]->(孙乾): 手下

(孙乾)-->(项玉娇)
(孙乾)-->(项玉燕)

@enduml
