#!/usr/bin/env bash
# shellcheck disable=SC1090

SCRIPT=/usr/local/etc/profile.d/bash_completion.sh
[[ -r $SCRIPT ]] && . $SCRIPT

SCRIPT=/usr/local/etc/profile.d/autojump.sh
[[ -r $SCRIPT ]] && . $SCRIPT

#if brew command command-not-found-init > /dev/null; then
#	eval "$(brew command-not-found-init)";
#fi
SCRIPT=/usr/local/Homebrew/Library/Taps/homebrew/homebrew-command-not-found/handler.sh
[[ -r $SCRIPT ]] && . $SCRIPT

export ENV="$HOME/Workspace.localized/env"
export PATH="$ENV/bin:$PATH"
