@startuml homebrew
skinparam usecase {
    BorderColor DarkSlateGray
    BackgroundColor DarkSeaGreen
    BackgroundColor<< dep >> DarkGoldenRod
}
(adns) << dep >>
(apache-spark)
(apr) << dep >>
(apr-util) << dep >>
(apr-util)->(apr)
(apr-util)->(openssl)
(archey)
(aria2)
(aria2)->(openssl)
(aria2)->(libssh2)
(autojump)
(bash)
(bash-completion@2)
(bash-completion@2)->(bash)
(bat)
(bfg)
(clang-format)
(cmake)
(colordiff)
(colorsvn)
(cscope) << dep >>
(ctags)
(curl)
(dep)
(dep)->(go)
(di)
(direnv)
(dmalloc)
(ethereum)
(exa)
(fd)
(figlet)
(file-formula)
(file-formula)->(libmagic)
(findutils)
(flake8)
(flake8)->(gdbm)
(flake8)->(openssl)
(flake8)->(readline)
(flake8)->(sqlite)
(flake8)->(xz)
(flake8)->(python)
(fontconfig) << dep >>
(fontconfig)->(libpng)
(fontconfig)->(freetype)
(freetype) << dep >>
(freetype)->(libpng)
(gawk)
(gawk)->(gettext)
(gawk)->(gmp)
(gawk)->(mpfr)
(gawk)->(readline)
(gd) << dep >>
(gd)->(libpng)
(gd)->(freetype)
(gd)->(fontconfig)
(gd)->(jpeg)
(gd)->(libtiff)
(gd)->(webp)
(gdbm) << dep >>
(geckodriver)
(gettext) << dep >>
(git)
(git)->(gettext)
(git)->(pcre2)
(git-lfs)
(glib) << dep >>
(glib)->(gettext)
(glib)->(libffi)
(glib)->(pcre)
(glib)->(gdbm)
(glib)->(openssl)
(glib)->(readline)
(glib)->(sqlite)
(glib)->(xz)
(glib)->(python)
(gmp) << dep >>
(gnu-sed)
(gnu-tar)
(gnupg)
(gnupg)->(adns)
(gnupg)->(gettext)
(gnupg)->(gmp)
(gnupg)->(libtasn1)
(gnupg)->(libunistring)
(gnupg)->(nettle)
(gnupg)->(libffi)
(gnupg)->(p11-kit)
(gnupg)->(openssl)
(gnupg)->(libevent)
(gnupg)->(unbound)
(gnupg)->(gnutls)
(gnupg)->(libgpg-error)
(gnupg)->(libassuan)
(gnupg)->(libgcrypt)
(gnupg)->(libksba)
(gnupg)->(libusb)
(gnupg)->(npth)
(gnupg)->(pinentry)
(gnutls) << dep >>
(gnutls)->(gmp)
(gnutls)->(gettext)
(gnutls)->(libunistring)
(gnutls)->(libidn2)
(gnutls)->(libtasn1)
(gnutls)->(nettle)
(gnutls)->(libffi)
(gnutls)->(p11-kit)
(gnutls)->(openssl)
(gnutls)->(libevent)
(gnutls)->(unbound)
(go) << dep >>
(go-bindata)
(go-bindata)->(go)
(gotags)
(gradle)
(graphviz)
(graphviz)->(libpng)
(graphviz)->(freetype)
(graphviz)->(fontconfig)
(graphviz)->(jpeg)
(graphviz)->(libtiff)
(graphviz)->(webp)
(graphviz)->(gd)
(graphviz)->(gettext)
(graphviz)->(libffi)
(graphviz)->(pcre)
(graphviz)->(gdbm)
(graphviz)->(openssl)
(graphviz)->(readline)
(graphviz)->(sqlite)
(graphviz)->(xz)
(graphviz)->(python)
(graphviz)->(glib)
(graphviz)->(jasper)
(graphviz)->(netpbm)
(graphviz)->(gts)
(graphviz)->(libtool)
(grep)
(grep)->(pcre)
(gts) << dep >>
(gts)->(gettext)
(gts)->(libffi)
(gts)->(pcre)
(gts)->(gdbm)
(gts)->(openssl)
(gts)->(readline)
(gts)->(sqlite)
(gts)->(xz)
(gts)->(python)
(gts)->(glib)
(gts)->(jpeg)
(gts)->(jasper)
(gts)->(libpng)
(gts)->(libtiff)
(gts)->(netpbm)
(httpie)
(httpie)->(gdbm)
(httpie)->(openssl)
(httpie)->(readline)
(httpie)->(sqlite)
(httpie)->(xz)
(httpie)->(python)
(icu4c) << dep >>
(iftop)
(ipython)
(ipython)->(gdbm)
(ipython)->(openssl)
(ipython)->(readline)
(ipython)->(sqlite)
(ipython)->(xz)
(ipython)->(python)
(ipython)->(zeromq)
(jasper) << dep >>
(jasper)->(jpeg)
(jemalloc)
(jpeg) << dep >>
(jq)
(jq)->(oniguruma)
(libassuan) << dep >>
(libassuan)->(libgpg-error)
(libevent) << dep >>
(libevent)->(openssl)
(libffi) << dep >>
(libgcrypt) << dep >>
(libgcrypt)->(libgpg-error)
(libgpg-error) << dep >>
(libidn2) << dep >>
(libidn2)->(gettext)
(libidn2)->(libunistring)
(libksba) << dep >>
(libksba)->(libgpg-error)
(libmagic) << dep >>
(libmemcached)
(libmemcached)->(openssl)
(libmemcached)->(libevent)
(libmemcached)->(memcached)
(libpng) << dep >>
(libssh2) << dep >>
(libssh2)->(openssl)
(libtasn1) << dep >>
(libtiff) << dep >>
(libtiff)->(jpeg)
(libtool) << dep >>
(libunistring) << dep >>
(libusb) << dep >>
(libyaml) << dep >>
(lua) << dep >>
(lz4) << dep >>
(macvim)
(macvim)->(cscope)
(macvim)->(lua)
(macvim)->(gdbm)
(macvim)->(openssl)
(macvim)->(readline)
(macvim)->(sqlite)
(macvim)->(xz)
(macvim)->(python)
(mariadb)
(mariadb)->(openssl)
(mas)
(maven)
(memcached)
(memcached)->(openssl)
(memcached)->(libevent)
(mitmproxy)
(mitmproxy)->(openssl)
(mitmproxy)->(gdbm)
(mitmproxy)->(readline)
(mitmproxy)->(sqlite)
(mitmproxy)->(xz)
(mitmproxy)->(python)
(mitmproxy)->(python@2)
(mitmproxy)->(protobuf)
(mongodb)
(mongodb)->(openssl)
(mongodb)->(gdbm)
(mongodb)->(readline)
(mongodb)->(sqlite)
(mongodb)->(python@2)
(mosh)
(mosh)->(gdbm)
(mosh)->(openssl)
(mosh)->(readline)
(mosh)->(sqlite)
(mosh)->(xz)
(mosh)->(python)
(mosh)->(python@2)
(mosh)->(protobuf)
(mpfr) << dep >>
(mpfr)->(gmp)
(ncdu)
(ncurses) << dep >>
(netpbm) << dep >>
(netpbm)->(jpeg)
(netpbm)->(jasper)
(netpbm)->(libpng)
(netpbm)->(libtiff)
(nettle) << dep >>
(nettle)->(gmp)
(node)
(node)->(icu4c)
(npth) << dep >>
(oniguruma) << dep >>
(openssl) << dep >>
(p11-kit) << dep >>
(p11-kit)->(libffi)
(p7zip)
(parallel)
(pcre) << dep >>
(pcre2) << dep >>
(perl) << dep >>
(pigz)
(pinentry) << dep >>
(pinentry)->(libgpg-error)
(pinentry)->(libassuan)
(pinentry-mac)
(protobuf) << dep >>
(protobuf)->(gdbm)
(protobuf)->(openssl)
(protobuf)->(readline)
(protobuf)->(sqlite)
(protobuf)->(xz)
(protobuf)->(python)
(protobuf)->(python@2)
(proxychains-ng)
(pstree)
(pup)
(pv)
(python) << dep >>
(python)->(gdbm)
(python)->(openssl)
(python)->(readline)
(python)->(sqlite)
(python)->(xz)
(python@2) << dep >>
(python@2)->(gdbm)
(python@2)->(openssl)
(python@2)->(readline)
(python@2)->(sqlite)
(q)
(rcs)
(readline) << dep >>
(ripgrep-bin)
(rlwrap)
(rlwrap)->(readline)
(rsync)
(ruby)
(ruby)->(libyaml)
(ruby)->(openssl)
(ruby)->(readline)
(shellcheck)
(sqlite) << dep >>
(sqlite)->(readline)
(ssh-copy-id)
(sshfs)
(sshfs)->(gettext)
(sshfs)->(libffi)
(sshfs)->(pcre)
(sshfs)->(gdbm)
(sshfs)->(openssl)
(sshfs)->(readline)
(sshfs)->(sqlite)
(sshfs)->(xz)
(sshfs)->(python)
(sshfs)->(glib)
(sshpass)
(subversion)
(subversion)->(apr)
(subversion)->(openssl)
(subversion)->(apr-util)
(subversion)->(gettext)
(subversion)->(lz4)
(subversion)->(perl)
(subversion)->(readline)
(subversion)->(sqlite)
(subversion)->(utf8proc)
(tcping)
(terminal-notifier)
(tomcat)
(tomcat-native)
(tomcat-native)->(apr)
(tomcat-native)->(openssl)
(tomcat-native)->(tomcat)
(trash)
(unbound) << dep >>
(unbound)->(openssl)
(unbound)->(libevent)
(utf8proc) << dep >>
(webp) << dep >>
(webp)->(jpeg)
(webp)->(libpng)
(webp)->(libtiff)
(wget)
(wget)->(gettext)
(wget)->(libunistring)
(wget)->(libidn2)
(wget)->(openssl)
(xz) << dep >>
(zeromq) << dep >>
(zsh)
(zsh)->(ncurses)
(zsh)->(pcre)
@enduml
