@startuml homebrew
skinparam usecase {
    BorderColor DarkSlateGray
    BackgroundColor DarkSeaGreen
    BackgroundColor<< req >> ForestGreen
    BackgroundColor<< dep >> DarkGoldenRod
}
(ant)
(ant)->(openjdk)
(apr) << dep >>
(apr-util) << dep >>
(apr-util)->(apr)
(apr-util)->(ca-certificates)
(apr-util)->(openssl@1.1)
(aria2)
(aria2)->(ca-certificates)
(aria2)->(libssh2)
(aria2)->(openssl@1.1)
(autojump)
(autojump)->(ca-certificates)
(autojump)->(gdbm)
(autojump)->(mpdecimal)
(autojump)->(openssl@1.1)
(autojump)->(python@3.10)
(autojump)->(readline)
(autojump)->(sqlite)
(autojump)->(xz)
(bash)
(bash-completion@2)
(bash-completion@2)->(bash)
(bat)
(bdw-gc) << dep >>
(bfg)
(bfg)->(openjdk)
(black)
(black)->(ca-certificates)
(black)->(gdbm)
(black)->(mpdecimal)
(black)->(openssl@1.1)
(black)->(python@3.10)
(black)->(readline)
(black)->(sqlite)
(black)->(xz)
(brotli) << dep >>
(c-ares) << dep >>
(ca-certificates) << dep >>
(choose-rust)
(clang-format)
(cmake)
(codespell)
(codespell)->(ca-certificates)
(codespell)->(gdbm)
(codespell)->(mpdecimal)
(codespell)->(openssl@1.1)
(codespell)->(python@3.10)
(codespell)->(readline)
(codespell)->(sqlite)
(codespell)->(xz)
(colordiff)
(colorsvn)
(croc)
(curl)
(curl)->(brotli)
(curl)->(ca-certificates)
(curl)->(gettext)
(curl)->(libidn2)
(curl)->(libnghttp2)
(curl)->(libssh2)
(curl)->(libunistring)
(curl)->(openldap)
(curl)->(openssl@1.1)
(curl)->(rtmpdump)
(curl)->(zstd)
(delve)
(di)
(direnv)
(eslint)
(eslint)->(brotli)
(eslint)->(c-ares)
(eslint)->(ca-certificates)
(eslint)->(icu4c)
(eslint)->(libnghttp2)
(eslint)->(libuv)
(eslint)->(node)
(eslint)->(openssl@1.1)
(exa)
(fd)
(fdupes)
(fdupes)->(pcre2)
(figlet)
(file-formula)
(file-formula)->(libmagic)
(flake8)
(flake8)->(ca-certificates)
(flake8)->(gdbm)
(flake8)->(mpdecimal)
(flake8)->(openssl@1.1)
(flake8)->(python@3.10)
(flake8)->(readline)
(flake8)->(sqlite)
(flake8)->(xz)
(freetype) << dep >>
(freetype)->(libpng)
(gawk)
(gawk)->(gettext)
(gawk)->(gmp)
(gawk)->(mpfr)
(gawk)->(readline)
(gdbm) << dep >>
(geoipupdate)
(gettext) << dep >>
(gh)
(git)
(git)->(gettext)
(git)->(pcre2)
(git-lfs)
(git-svn)
(git-svn)->(apr)
(git-svn)->(apr-util)
(git-svn)->(ca-certificates)
(git-svn)->(gettext)
(git-svn)->(git)
(git-svn)->(lz4)
(git-svn)->(openssl@1.1)
(git-svn)->(pcre2)
(git-svn)->(subversion)
(git-svn)->(utf8proc)
(gmp) << dep >>
(gnu-sed)
(gnu-tar)
(gnupg)
(gnupg)->(bdw-gc)
(gnupg)->(ca-certificates)
(gnupg)->(gettext)
(gnupg)->(gmp)
(gnupg)->(gnutls)
(gnupg)->(guile)
(gnupg)->(libassuan)
(gnupg)->(libevent)
(gnupg)->(libffi)
(gnupg)->(libgcrypt)
(gnupg)->(libgpg-error)
(gnupg)->(libidn2)
(gnupg)->(libksba)
(gnupg)->(libnghttp2)
(gnupg)->(libtasn1)
(gnupg)->(libtool)
(gnupg)->(libunistring)
(gnupg)->(libusb)
(gnupg)->(m4)
(gnupg)->(nettle)
(gnupg)->(npth)
(gnupg)->(openssl@1.1)
(gnupg)->(p11-kit)
(gnupg)->(pinentry)
(gnupg)->(pkg-config)
(gnupg)->(readline)
(gnupg)->(unbound)
(gnutls) << dep >>
(gnutls)->(bdw-gc)
(gnutls)->(ca-certificates)
(gnutls)->(gettext)
(gnutls)->(gmp)
(gnutls)->(guile)
(gnutls)->(libevent)
(gnutls)->(libffi)
(gnutls)->(libidn2)
(gnutls)->(libnghttp2)
(gnutls)->(libtasn1)
(gnutls)->(libtool)
(gnutls)->(libunistring)
(gnutls)->(m4)
(gnutls)->(nettle)
(gnutls)->(openssl@1.1)
(gnutls)->(p11-kit)
(gnutls)->(pkg-config)
(gnutls)->(readline)
(gnutls)->(unbound)
(go)
(gomodifytags)
(gopls)
(gost)
(gotags)
(gotests)
(gotop)
(gradle)
(gradle)->(openjdk)
(guile) << dep >>
(guile)->(bdw-gc)
(guile)->(gmp)
(guile)->(libffi)
(guile)->(libtool)
(guile)->(libunistring)
(guile)->(m4)
(guile)->(pkg-config)
(guile)->(readline)
(hexyl)
(htop)
(htop)->(ncurses)
(httpie)
(httpie)->(ca-certificates)
(httpie)->(gdbm)
(httpie)->(mpdecimal)
(httpie)->(openssl@1.1)
(httpie)->(python@3.10)
(httpie)->(readline)
(httpie)->(sqlite)
(httpie)->(xz)
(httping)
(httping)->(ca-certificates)
(httping)->(gettext)
(httping)->(openssl@1.1)
(icu4c) << dep >>
(iftop)
(iperf3)
(iperf3)->(ca-certificates)
(iperf3)->(openssl@1.1)
(ipython)
(ipython)->(ca-certificates)
(ipython)->(gdbm)
(ipython)->(libsodium)
(ipython)->(mpdecimal)
(ipython)->(openssl@1.1)
(ipython)->(python@3.10)
(ipython)->(readline)
(ipython)->(six)
(ipython)->(sqlite)
(ipython)->(xz)
(ipython)->(zeromq)
(jq)
(jq)->(oniguruma)
(libassuan) << dep >>
(libassuan)->(libgpg-error)
(libevent) << dep >>
(libevent)->(ca-certificates)
(libevent)->(openssl@1.1)
(libffi) << dep >>
(libgcrypt) << dep >>
(libgcrypt)->(libgpg-error)
(libgpg-error) << dep >>
(libidn2) << dep >>
(libidn2)->(gettext)
(libidn2)->(libunistring)
(libksba) << dep >>
(libksba)->(libgpg-error)
(libmagic) << dep >>
(libnghttp2) << dep >>
(libpng) << dep >>
(libsodium) << dep >>
(libssh2) << dep >>
(libssh2)->(ca-certificates)
(libssh2)->(openssl@1.1)
(libtasn1) << dep >>
(libtermkey) << dep >>
(libtermkey)->(unibilium)
(libtool) << dep >>
(libtool)->(m4)
(libunistring) << dep >>
(libusb) << dep >>
(libuv) << dep >>
(liquibase)
(liquibase)->(openjdk)
(luajit-openresty) << dep >>
(luv) << dep >>
(luv)->(libuv)
(lz4) << dep >>
(m4) << dep >>
(macos-trash)
(mas)
(maven)
(maven)->(openjdk)
(miniserve)
(mitmproxy)
(mitmproxy)->(ca-certificates)
(mitmproxy)->(gdbm)
(mitmproxy)->(mpdecimal)
(mitmproxy)->(openssl@1.1)
(mitmproxy)->(protobuf)
(mitmproxy)->(python@3.9)
(mitmproxy)->(readline)
(mitmproxy)->(six)
(mitmproxy)->(sqlite)
(mitmproxy)->(xz)
(moonfruit/tap/ethr)
(moonfruit/tap/openssl@1.0)
(moonfruit/tap/sshpass)
(moonfruit/tap/wlp-webprofile8)
(moonfruit/tap/wlp-webprofile8)->(openjdk)
(mosh)
(mosh)->(protobuf)
(mosh)->(six)
(mpdecimal) << dep >>
(mpfr) << dep >>
(mpfr)->(gmp)
(msgpack) << dep >>
(ncdu)
(ncdu)->(ncurses)
(ncurses) << dep >>
(neovim)
(neovim)->(gettext)
(neovim)->(libtermkey)
(neovim)->(libuv)
(neovim)->(luajit-openresty)
(neovim)->(luv)
(neovim)->(msgpack)
(neovim)->(tree-sitter)
(neovim)->(unibilium)
(nettle) << dep >>
(nettle)->(gmp)
(node) << dep >>
(node)->(brotli)
(node)->(c-ares)
(node)->(ca-certificates)
(node)->(icu4c)
(node)->(libnghttp2)
(node)->(libuv)
(node)->(openssl@1.1)
(npth) << dep >>
(oniguruma) << dep >>
(openjdk)
(openjdk@8)
(openjdk@8)->(freetype)
(openjdk@8)->(libpng)
(openldap) << dep >>
(openldap)->(ca-certificates)
(openldap)->(openssl@1.1)
(openssl@1.1) << dep >>
(openssl@1.1)->(ca-certificates)
(p11-kit) << dep >>
(p11-kit)->(ca-certificates)
(p11-kit)->(libffi)
(p11-kit)->(libtasn1)
(p7zip)
(pandoc)
(parallel)
(pcre) << dep >>
(pcre2) << dep >>
(pigz)
(pinentry) << dep >>
(pinentry)->(libassuan)
(pinentry)->(libgpg-error)
(pinentry-mac)
(pinentry-mac)->(gettext)
(pinentry-mac)->(libassuan)
(pinentry-mac)->(libgpg-error)
(pipgrip)
(pipgrip)->(ca-certificates)
(pipgrip)->(gdbm)
(pipgrip)->(mpdecimal)
(pipgrip)->(openssl@1.1)
(pipgrip)->(python@3.10)
(pipgrip)->(readline)
(pipgrip)->(six)
(pipgrip)->(sqlite)
(pipgrip)->(xz)
(pkg-config) << dep >>
(popt) << dep >>
(prettier)
(prettier)->(brotli)
(prettier)->(c-ares)
(prettier)->(ca-certificates)
(prettier)->(icu4c)
(prettier)->(libnghttp2)
(prettier)->(libuv)
(prettier)->(node)
(prettier)->(openssl@1.1)
(protobuf) << dep >>
(protobuf)->(six)
(pstree)
(pup)
(pv)
(python@3.10) << dep >>
(python@3.10)->(ca-certificates)
(python@3.10)->(gdbm)
(python@3.10)->(mpdecimal)
(python@3.10)->(openssl@1.1)
(python@3.10)->(readline)
(python@3.10)->(sqlite)
(python@3.10)->(xz)
(python@3.9) << dep >>
(python@3.9)->(ca-certificates)
(python@3.9)->(gdbm)
(python@3.9)->(mpdecimal)
(python@3.9)->(openssl@1.1)
(python@3.9)->(readline)
(python@3.9)->(sqlite)
(python@3.9)->(xz)
(q)
(q)->(ca-certificates)
(q)->(gdbm)
(q)->(mpdecimal)
(q)->(openssl@1.1)
(q)->(python@3.9)
(q)->(readline)
(q)->(six)
(q)->(sqlite)
(q)->(xz)
(rcs)
(readline) << dep >>
(ripgrep)
(ripgrep)->(pcre2)
(rlwrap)
(rlwrap)->(readline)
(rsync)
(rsync)->(ca-certificates)
(rsync)->(lz4)
(rsync)->(openssl@1.1)
(rsync)->(popt)
(rsync)->(xxhash)
(rsync)->(zstd)
(rtmpdump) << dep >>
(rtmpdump)->(ca-certificates)
(rtmpdump)->(openssl@1.1)
(rust)
(rust)->(ca-certificates)
(rust)->(libssh2)
(rust)->(openssl@1.1)
(rust)->(pkg-config)
(shellcheck)
(shfmt)
(six) << dep >>
(sqlite) << dep >>
(sqlite)->(readline)
(stylua)
(subversion)
(subversion)->(apr)
(subversion)->(apr-util)
(subversion)->(ca-certificates)
(subversion)->(gettext)
(subversion)->(lz4)
(subversion)->(openssl@1.1)
(subversion)->(utf8proc)
(tcping)
(terminal-notifier)
(testssl)
(testssl)->(ca-certificates)
(testssl)->(openssl@1.1)
(tmux)
(tmux)->(ca-certificates)
(tmux)->(libevent)
(tmux)->(ncurses)
(tmux)->(openssl@1.1)
(tmux)->(utf8proc)
(tokei)
(tomcat-native)
(tomcat-native)->(apr)
(tomcat-native)->(ca-certificates)
(tomcat-native)->(openjdk)
(tomcat-native)->(openssl@1.1)
(tomcat@8)
(tomcat@8)->(openjdk)
(tomcat@9)
(tomcat@9)->(openjdk)
(tree-sitter) << dep >>
(typescript)
(typescript)->(brotli)
(typescript)->(c-ares)
(typescript)->(ca-certificates)
(typescript)->(icu4c)
(typescript)->(libnghttp2)
(typescript)->(libuv)
(typescript)->(node)
(typescript)->(openssl@1.1)
(ugrep)
(ugrep)->(pcre2)
(ugrep)->(xz)
(unbound) << dep >>
(unbound)->(ca-certificates)
(unbound)->(libevent)
(unbound)->(libnghttp2)
(unbound)->(openssl@1.1)
(unibilium) << dep >>
(utf8proc) << dep >>
(wget)
(wget)->(ca-certificates)
(wget)->(gettext)
(wget)->(libidn2)
(wget)->(libunistring)
(wget)->(openssl@1.1)
(xxhash) << dep >>
(xz) << dep >>
(yarn)
(ykdl)
(ykdl)->(ca-certificates)
(ykdl)->(gdbm)
(ykdl)->(mpdecimal)
(ykdl)->(openssl@1.1)
(ykdl)->(python@3.10)
(ykdl)->(readline)
(ykdl)->(sqlite)
(ykdl)->(xz)
(youtube-dl)
(youtube-dl)->(ca-certificates)
(youtube-dl)->(gdbm)
(youtube-dl)->(mpdecimal)
(youtube-dl)->(openssl@1.1)
(youtube-dl)->(python@3.10)
(youtube-dl)->(readline)
(youtube-dl)->(sqlite)
(youtube-dl)->(xz)
(zeromq) << dep >>
(zeromq)->(libsodium)
(zsh)
(zsh)->(ncurses)
(zsh)->(pcre)
(zstd) << dep >>
@enduml
