@startuml homebrew
skinparam usecase {
    BorderColor DarkSlateGray
    BackgroundColor DarkSeaGreen
    BackgroundColor<< dep >> DarkGoldenRod
}
(apr) << dep >>
(apr-util) << dep >>
(apr-util)->(apr)
(apr-util)->(openssl)
(archey)
(aria2)
(aria2)->(openssl)
(aria2)->(libssh2)
(autojump)
(bash)
(bash-completion@2)
(bash-completion@2)->(bash)
(bat)
(bazaar)
(bfg)
(binaryen)
(boxes)
(c-ares) << dep >>
(clang-format)
(cmake)
(colordiff)
(colorsvn)
(cscope) << dep >>
(ctags)
(dep)
(dep)->(go)
(di)
(direnv)
(dmalloc)
(emscripten)
(emscripten)->(icu4c)
(emscripten)->(node)
(emscripten)->(gdbm)
(emscripten)->(openssl)
(emscripten)->(readline)
(emscripten)->(sqlite)
(emscripten)->(python@2)
(emscripten)->(yuicompressor)
(ethereum)
(figlet)
(file-formula)
(file-formula)->(libmagic)
(findutils)
(flake8)
(flake8)->(gdbm)
(flake8)->(openssl)
(flake8)->(readline)
(flake8)->(sqlite)
(flake8)->(xz)
(flake8)->(python)
(fontconfig) << dep >>
(fontconfig)->(libpng)
(fontconfig)->(freetype)
(freetype) << dep >>
(freetype)->(libpng)
(gawk)
(gawk)->(gettext)
(gawk)->(gmp)
(gawk)->(mpfr)
(gawk)->(readline)
(gd) << dep >>
(gd)->(libpng)
(gd)->(freetype)
(gd)->(fontconfig)
(gd)->(jpeg)
(gd)->(libtiff)
(gd)->(webp)
(gdbm) << dep >>
(gettext) << dep >>
(git)
(git)->(gettext)
(git)->(pcre2)
(git-lfs)
(glib) << dep >>
(glib)->(gettext)
(glib)->(libffi)
(glib)->(pcre)
(gmp) << dep >>
(gnu-sed)
(gnu-tar)
(go) << dep >>
(go-bindata)
(go-bindata)->(go)
(gotags)
(gradle)
(graphviz)
(graphviz)->(libtool)
(graphviz)->(libpng)
(graphviz)->(freetype)
(graphviz)->(fontconfig)
(graphviz)->(jpeg)
(graphviz)->(libtiff)
(graphviz)->(webp)
(graphviz)->(gd)
(grep)
(grep)->(pcre)
(httpie)
(httpie)->(gdbm)
(httpie)->(openssl)
(httpie)->(readline)
(httpie)->(sqlite)
(httpie)->(xz)
(httpie)->(python)
(icu4c) << dep >>
(iftop)
(ipython)
(ipython)->(gdbm)
(ipython)->(openssl)
(ipython)->(readline)
(ipython)->(sqlite)
(ipython)->(xz)
(ipython)->(python)
(ipython)->(zeromq)
(jemalloc)
(jpeg) << dep >>
(jq)
(jq)->(oniguruma)
(libev) << dep >>
(libevent) << dep >>
(libevent)->(openssl)
(libffi) << dep >>
(libidn2) << dep >>
(libidn2)->(gettext)
(libidn2)->(libunistring)
(libmagic) << dep >>
(libmemcached)
(libmemcached)->(openssl)
(libmemcached)->(libevent)
(libmemcached)->(memcached)
(libpng) << dep >>
(libsodium) << dep >>
(libssh2) << dep >>
(libssh2)->(openssl)
(libtiff) << dep >>
(libtiff)->(jpeg)
(libtool) << dep >>
(libunistring) << dep >>
(libyaml) << dep >>
(lua) << dep >>
(lz4) << dep >>
(macvim)
(macvim)->(cscope)
(macvim)->(lua)
(macvim)->(gdbm)
(macvim)->(openssl)
(macvim)->(readline)
(macvim)->(sqlite)
(macvim)->(xz)
(macvim)->(python)
(mariadb)
(mariadb)->(openssl)
(mas)
(mas)->(trash)
(maven)
(mbedtls) << dep >>
(memcached)
(memcached)->(openssl)
(memcached)->(libevent)
(mitmproxy)
(mitmproxy)->(openssl)
(mitmproxy)->(gdbm)
(mitmproxy)->(readline)
(mitmproxy)->(sqlite)
(mitmproxy)->(xz)
(mitmproxy)->(python)
(mitmproxy)->(python@2)
(mitmproxy)->(protobuf)
(mosh)
(mosh)->(gdbm)
(mosh)->(openssl)
(mosh)->(readline)
(mosh)->(sqlite)
(mosh)->(python@2)
(mosh)->(protobuf)
(mpfr) << dep >>
(mpfr)->(gmp)
(ncurses) << dep >>
(node)
(node)->(icu4c)
(oniguruma) << dep >>
(openssl) << dep >>
(p7zip)
(parallel)
(pcre) << dep >>
(pcre2) << dep >>
(perl) << dep >>
(pigz)
(protobuf)
(protobuf)->(gdbm)
(protobuf)->(openssl)
(protobuf)->(readline)
(protobuf)->(sqlite)
(protobuf)->(xz)
(protobuf)->(python)
(protobuf)->(python@2)
(proxychains-ng)
(pstree)
(pup)
(pv)
(python) << dep >>
(python)->(gdbm)
(python)->(openssl)
(python)->(readline)
(python)->(sqlite)
(python)->(xz)
(python@2) << dep >>
(python@2)->(gdbm)
(python@2)->(openssl)
(python@2)->(readline)
(python@2)->(sqlite)
(q)
(rcs)
(readline) << dep >>
(rlwrap)
(rlwrap)->(readline)
(rsync)
(ruby)
(ruby)->(libyaml)
(ruby)->(openssl)
(ruby)->(readline)
(shadowsocks-libev)
(shadowsocks-libev)->(c-ares)
(shadowsocks-libev)->(libev)
(shadowsocks-libev)->(libsodium)
(shadowsocks-libev)->(mbedtls)
(shadowsocks-libev)->(pcre)
(shellcheck)
(sqlite) << dep >>
(sqlite)->(readline)
(ssh-copy-id)
(sshfs)
(sshfs)->(gettext)
(sshfs)->(libffi)
(sshfs)->(pcre)
(sshfs)->(glib)
(sshpass)
(stunnel)
(stunnel)->(openssl)
(subversion)
(subversion)->(apr)
(subversion)->(openssl)
(subversion)->(apr-util)
(subversion)->(gettext)
(subversion)->(lz4)
(subversion)->(perl)
(subversion)->(readline)
(subversion)->(sqlite)
(subversion)->(utf8proc)
(terminal-notifier)
(thefuck)
(thefuck)->(gdbm)
(thefuck)->(openssl)
(thefuck)->(readline)
(thefuck)->(sqlite)
(thefuck)->(xz)
(thefuck)->(python)
(tomcat)
(tomcat-native)
(tomcat-native)->(apr)
(tomcat-native)->(openssl)
(tomcat-native)->(tomcat)
(trash)
(tree)
(utf8proc) << dep >>
(wabt)
(webp) << dep >>
(webp)->(jpeg)
(webp)->(libpng)
(wget)
(wget)->(gettext)
(wget)->(libunistring)
(wget)->(libidn2)
(wget)->(openssl)
(xz) << dep >>
(yarn)
(yarn)->(icu4c)
(yarn)->(node)
(yuicompressor) << dep >>
(zeromq) << dep >>
(zsh)
(zsh)->(ncurses)
@enduml
