#!/bin/bash
layout_node() {
	if [[ $1 == 14 || $1 == lts ]]; then
		JAVA_HOME=$(java-home -n graalvm)
		PATH_add "$JAVA_HOME/bin"

		export CPPFLAGS=-I$JAVA_HOME/languages/js/include

	elif [[ -n $1 ]]; then
		PATH_add "/opt/homebrew/opt/node@$1/bin"

		export LDFLAGS=-L/opt/homebrew/opt/node@$1/lib
		export CPPFLAGS=-I/opt/homebrew/opt/node@$1/include
	fi

	PATH_add node_modules/.bin
}

venv_type() {
	"$1" <<END
import pkgutil
for pkg in ('venv', 'virtualenv'):
	if pkgutil.find_loader(pkg):
		print(pkg)
		break
END
}

layout_python() {
	local python=${1:-python}
	[[ $# -gt 0 ]] && shift

	if [[ ! -r venv/bin/activate ]]; then
		log_status "creating virtualenv"
		case $(venv_type "$python") in
		"venv")
			"$python" -m venv "$@" venv
			;;
		"virtualenv")
			virtualenv "--python=$python" "$@" venv
			;;
		*)
			log_error "Error: neither venv nor virtualenv are available."
			return 1
			;;
		esac
		if [[ -x venv/bin/pip ]]; then
			if [[ -r requirements.txt ]]; then
				REQUIREMENTS=(-r requirements.txt)
			fi
			venv/bin/pip install -U pip setuptools wheel "${REQUIREMENTS[@]}"
		fi
	fi

	# shellcheck disable=SC1091
	source venv/bin/activate
	unset PS1
}

layout_java() {
	local version=$1
	if [[ -n $version ]]; then
		JAVA_HOME=$(java-home -v "$version")
		export JAVA_HOME
		PATH_add "$JAVA_HOME/bin"
	fi

	export MAVEN_REPO_URL=http://10.1.2.32/nexus/repository
}
