language: en,en-GB
allowCompoundWords: true
ignoreRandomStrings: true
words:
  - astrovim
  - augroup
  - autocmd
  - autocmds
  - basedpyright
  - bashls
  - ccstatusline
  - cips
  - clangd
  - cmux
  - cnaps
  - codelldb
  - CPPFLAGS
  - cssls
  - deque
  - direnv
  - dkmooncat
  - dkmoonfruit
  - dmalloc
  - dnsctl
  - dockerls
  - eip
  - elif
  - enduml
  - env
  - envrc
  - esac
  - esqlc
  - fakeip
  - gelf
  - ghostty
  - gingkoo
  - gitee
  - gitmodules
  - gofumpt
  - goimports
  - gomodifytags
  - gopls
  - gpms
  - graalvm
  - groovyls
  - gsub
  - haos
  - heiyu
  - inreplace
  - iterm
  - jdbc
  - jsonls
  - ktlint
  - lazyvim
  - LDFLAGS
  - lldb
  - lspconfig
  - lualine
  - lzc
  - maven
  - mcpserver
  - mdns
  - moonfruit
  - mybatis
  - nanocloud
  - noremap
  - npmjs
  - nvim
  - nvimtools
  - oradb
  - osascript
  - pcall
  - pcre
  - plaintex
  - pyright
  - qwen
  - rubocop
  - setaf
  - shfmt
  - shopt
  - skinparam
  - sonoma
  - startuml
  - swiftc
  - taplo
  - tavily
  - temurin
  - tput
  - tunnelblick
  - typst
  - upgrader
  - utun
  - venv
  - virtualenv
  - xctoolchain
  - xipcloud
  - xxoo
  - yamlls
  - yanky
  - zashboard
  - zstd
